// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wjafXWEvDytFogT7SiMy2v
// Component: oQ9IYAdIiE5g

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: WB4OwDxc51ck/component
import { ApiFetcherComponent } from "../../../utils/ApiFetcherComponent"; // plasmic-import: kxxsrihQ2d7W/codeComponent
import Button from "../../Button"; // plasmic-import: IoZvAstVrNqa/component
import RedirectUserToLoginPage from "../../RedirectUserToLoginPage"; // plasmic-import: 0wFpBWYaqpsM/component

import { useScreenVariants as useScreenVariantsjEqVmdAbnKYc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jEqVmdAbnKYc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_inlab.module.css"; // plasmic-import: wjafXWEvDytFogT7SiMy2v/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: oQ9IYAdIiE5g/css

import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: YlP_1riCYk4W/icon
import SearchsvgIcon from "./icons/PlasmicIcon__Searchsvg"; // plasmic-import: YIqBWKHX3AVs/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: I6pxicA96WJm/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: NFXRoS4oqKav/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: vsUaT3pPwdP4/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  patientListsearch?: p.Flex<"div">;
  pageContent?: p.Flex<"div">;
  searchsetting?: p.Flex<"div">;
  settingIcon?: p.Flex<"svg">;
  searchbar?: p.Flex<typeof TextInput>;
  apiFetcherComponent?: p.Flex<typeof ApiFetcherComponent>;
  patientCards?: p.Flex<"div">;
  firstlastName?: p.Flex<"div">;
  wardroom?: p.Flex<"div">;
  roombed?: p.Flex<"div">;
  ward?: p.Flex<"div">;
  patientDataButtons?: p.Flex<"div">;
  commentButton?: p.Flex<typeof Button>;
  text?: p.Flex<"div">;
  redirectUserToLoginPage?: p.Flex<typeof RedirectUserToLoginPage>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof p.useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "searchbar.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          hasVariant(globalVariants, "screen", "mobileFirst") ? `` : ``
      },
      {
        path: "commentButton.isDisabled",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjEqVmdAbnKYc()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"patientListsearch"}
        data-plasmic-override={overrides.patientListsearch}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens,
          plasmic_plasmic_rich_components_css.plasmic_tokens,
          sty.patientListsearch
        )}
      >
        <div
          data-plasmic-name={"pageContent"}
          data-plasmic-override={overrides.pageContent}
          className={classNames(projectcss.all, sty.pageContent)}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"searchsetting"}
            data-plasmic-override={overrides.searchsetting}
            hasGap={true}
            className={classNames(projectcss.all, sty.searchsetting)}
          >
            <MenuIcon
              data-plasmic-name={"settingIcon"}
              data-plasmic-override={overrides.settingIcon}
              className={classNames(projectcss.all, sty.settingIcon)}
              onClick={async event => {
                const $steps = {};

                $steps["goToSetting"] = true
                  ? (() => {
                      const actionArgs = { destination: `/user/setting` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToSetting"] != null &&
                  typeof $steps["goToSetting"] === "object" &&
                  typeof $steps["goToSetting"].then === "function"
                ) {
                  $steps["goToSetting"] = await $steps["goToSetting"];
                }
              }}
              role={"img"}
            />

            <TextInput
              data-plasmic-name={"searchbar"}
              data-plasmic-override={overrides.searchbar}
              className={classNames("__wab_instance", sty.searchbar)}
              onChange={async (...eventArgs: any) => {
                ((...eventArgs) => {
                  p.generateStateOnChangeProp($state, ["searchbar", "value"])(
                    (e => e.target?.value).apply(null, eventArgs)
                  );
                }).apply(null, eventArgs);
                (async event => {
                  const $steps = {};
                }).apply(null, eventArgs);
              }}
              placeholder={
                "\u0646\u0627\u0645\u060c \u0646\u0627\u0645 \u062e\u0627\u0646\u0648\u0627\u062f\u06af\u06cc\u060c \u0634\u0645\u0627\u0631\u0647 \u067e\u0631\u0648\u0646\u062f\u0647\u060c \u06a9\u062f \u0645\u0644\u06cc\u060c \u06a9\u062f \u067e\u06a9\u0633 \u0631\u0627 \u0648\u0627\u0631\u062f \u06a9\u0646\u06cc\u062f"
              }
              showStartIcon={true}
              startIcon={
                <SearchsvgIcon
                  className={classNames(projectcss.all, sty.svg__nPrTh)}
                  role={"img"}
                />
              }
              value={
                p.generateStateValueProp($state, ["searchbar", "value"]) ?? ""
              }
            />
          </p.Stack>
          <ApiFetcherComponent
            data-plasmic-name={"apiFetcherComponent"}
            data-plasmic-override={overrides.apiFetcherComponent}
            className={classNames("__wab_instance", sty.apiFetcherComponent)}
            delay={400}
            headers={(() => {
              try {
                return { "X-Namespace": 2 };
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
            method={"GET"}
            path={`/api/v2/domain/patients?search_name=${$state.searchbar.value}&offset=0&limit=20`}
          >
            <ph.DataCtxReader>
              {$ctx =>
                (_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                  (() => {
                    try {
                      return $ctx.fetched_data.data.patients;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()
                ).map((__plasmic_item_0, __plasmic_idx_0) => {
                  const currentItem = __plasmic_item_0;
                  const currentIndex = __plasmic_idx_0;
                  return (
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"patientCards"}
                      data-plasmic-override={overrides.patientCards}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.patientCards)}
                      key={currentIndex}
                    >
                      <div
                        data-plasmic-name={"firstlastName"}
                        data-plasmic-override={overrides.firstlastName}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.firstlastName
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return (
                                currentItem.first_name +
                                " " +
                                currentItem.last_name
                              );
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                      <div
                        data-plasmic-name={"wardroom"}
                        data-plasmic-override={overrides.wardroom}
                        className={classNames(projectcss.all, sty.wardroom)}
                      >
                        <div
                          data-plasmic-name={"roombed"}
                          data-plasmic-override={overrides.roombed}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.roombed
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return currentItem.room + " " + currentItem.bed;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        <div
                          data-plasmic-name={"ward"}
                          data-plasmic-override={overrides.ward}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.ward
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return currentItem.ward.name;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"patientDataButtons"}
                        data-plasmic-override={overrides.patientDataButtons}
                        className={classNames(
                          projectcss.all,
                          sty.patientDataButtons
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__bwGuW)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"18px"}
                          onClick={async event => {
                            const $steps = {};

                            $steps["goToPatientProfile"] = true
                              ? (() => {
                                  const actionArgs = {
                                    destination: `/patient/${(() => {
                                      try {
                                        return currentItem.profile_id;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()}/${(() => {
                                      try {
                                        return (
                                          currentItem.first_name +
                                          " " +
                                          currentItem.last_name
                                        );
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()}/profile`
                                  };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      __nextRouter?.push(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["goToPatientProfile"] != null &&
                              typeof $steps["goToPatientProfile"] ===
                                "object" &&
                              typeof $steps["goToPatientProfile"].then ===
                                "function"
                            ) {
                              $steps["goToPatientProfile"] = await $steps[
                                "goToPatientProfile"
                              ];
                            }
                          }}
                          src={{
                            src: "/plasmic/inlab/images/group2063.svg",
                            fullWidth: 18.77,
                            fullHeight: 20.34,
                            aspectRatio: 0.904762
                          }}
                        />

                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ekG1)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"15px"}
                          onClick={async event => {
                            const $steps = {};

                            $steps["goToImagingReport1"] = true
                              ? (() => {
                                  const actionArgs = {
                                    destination: `/patient/${(() => {
                                      try {
                                        return currentItem.profile_id;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()}/${(() => {
                                      try {
                                        return (
                                          currentItem.first_name +
                                          " " +
                                          currentItem.last_name
                                        );
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()}/report/list`
                                  };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      __nextRouter?.push(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["goToImagingReport1"] != null &&
                              typeof $steps["goToImagingReport1"] ===
                                "object" &&
                              typeof $steps["goToImagingReport1"].then ===
                                "function"
                            ) {
                              $steps["goToImagingReport1"] = await $steps[
                                "goToImagingReport1"
                              ];
                            }
                          }}
                          src={{
                            src: "/plasmic/inlab/images/group376.svg",
                            fullWidth: 19.424,
                            fullHeight: 19.98,
                            aspectRatio: 1
                          }}
                        />

                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__hy0Zx)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"15px"}
                          onClick={async event => {
                            const $steps = {};

                            $steps["goToLaboratoryData"] = true
                              ? (() => {
                                  const actionArgs = {
                                    destination: `/patient/${(() => {
                                      try {
                                        return currentItem.profile_id;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()}/${(() => {
                                      try {
                                        return (
                                          currentItem.first_name +
                                          " " +
                                          currentItem.last_name
                                        );
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()}/lab`
                                  };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      __nextRouter?.push(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["goToLaboratoryData"] != null &&
                              typeof $steps["goToLaboratoryData"] ===
                                "object" &&
                              typeof $steps["goToLaboratoryData"].then ===
                                "function"
                            ) {
                              $steps["goToLaboratoryData"] = await $steps[
                                "goToLaboratoryData"
                              ];
                            }
                          }}
                          src={{
                            src: "/plasmic/inlab/images/group384.svg",
                            fullWidth: 14.575,
                            fullHeight: 18.692,
                            aspectRatio: 0.789474
                          }}
                        />
                      </div>
                    </p.Stack>
                  );
                })
              }
            </ph.DataCtxReader>
          </ApiFetcherComponent>
        </div>
        <Button
          data-plasmic-name={"commentButton"}
          data-plasmic-override={overrides.commentButton}
          className={classNames("__wab_instance", sty.commentButton)}
          color={"blue"}
          isDisabled={p.generateStateValueProp($state, [
            "commentButton",
            "isDisabled"
          ])}
          link={
            "https://docs.google.com/forms/d/e/1FAIpQLSeVxCqYPfByUBPROGdXtrp3dX10uL6SCMHqNAMy05YBsSgzng/viewform"
          }
          onIsDisabledChange={(...eventArgs) => {
            p.generateStateOnChangeProp($state, [
              "commentButton",
              "isDisabled"
            ])(eventArgs[0]);
          }}
          shape={"round"}
          size={"compact"}
          target={true}
        >
          <Icon2Icon
            className={classNames(projectcss.all, sty.svg__ijSG)}
            role={"img"}
          />

          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            {""}
          </div>
        </Button>
        <RedirectUserToLoginPage
          data-plasmic-name={"redirectUserToLoginPage"}
          data-plasmic-override={overrides.redirectUserToLoginPage}
          className={classNames("__wab_instance", sty.redirectUserToLoginPage)}
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  patientListsearch: [
    "patientListsearch",
    "pageContent",
    "searchsetting",
    "settingIcon",
    "searchbar",
    "apiFetcherComponent",
    "patientCards",
    "firstlastName",
    "wardroom",
    "roombed",
    "ward",
    "patientDataButtons",
    "commentButton",
    "text",
    "redirectUserToLoginPage"
  ],
  pageContent: [
    "pageContent",
    "searchsetting",
    "settingIcon",
    "searchbar",
    "apiFetcherComponent",
    "patientCards",
    "firstlastName",
    "wardroom",
    "roombed",
    "ward",
    "patientDataButtons"
  ],
  searchsetting: ["searchsetting", "settingIcon", "searchbar"],
  settingIcon: ["settingIcon"],
  searchbar: ["searchbar"],
  apiFetcherComponent: [
    "apiFetcherComponent",
    "patientCards",
    "firstlastName",
    "wardroom",
    "roombed",
    "ward",
    "patientDataButtons"
  ],
  patientCards: [
    "patientCards",
    "firstlastName",
    "wardroom",
    "roombed",
    "ward",
    "patientDataButtons"
  ],
  firstlastName: ["firstlastName"],
  wardroom: ["wardroom", "roombed", "ward"],
  roombed: ["roombed"],
  ward: ["ward"],
  patientDataButtons: ["patientDataButtons"],
  commentButton: ["commentButton", "text"],
  text: ["text"],
  redirectUserToLoginPage: ["redirectUserToLoginPage"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  patientListsearch: "div";
  pageContent: "div";
  searchsetting: "div";
  settingIcon: "svg";
  searchbar: typeof TextInput;
  apiFetcherComponent: typeof ApiFetcherComponent;
  patientCards: "div";
  firstlastName: "div";
  wardroom: "div";
  roombed: "div";
  ward: "div";
  patientDataButtons: "div";
  commentButton: typeof Button;
  text: "div";
  redirectUserToLoginPage: typeof RedirectUserToLoginPage;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "patientListsearch") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("patientListsearch"),
  {
    // Helper components rendering sub-elements
    pageContent: makeNodeComponent("pageContent"),
    searchsetting: makeNodeComponent("searchsetting"),
    settingIcon: makeNodeComponent("settingIcon"),
    searchbar: makeNodeComponent("searchbar"),
    apiFetcherComponent: makeNodeComponent("apiFetcherComponent"),
    patientCards: makeNodeComponent("patientCards"),
    firstlastName: makeNodeComponent("firstlastName"),
    wardroom: makeNodeComponent("wardroom"),
    roombed: makeNodeComponent("roombed"),
    ward: makeNodeComponent("ward"),
    patientDataButtons: makeNodeComponent("patientDataButtons"),
    commentButton: makeNodeComponent("commentButton"),
    text: makeNodeComponent("text"),
    redirectUserToLoginPage: makeNodeComponent("redirectUserToLoginPage"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
