// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wjafXWEvDytFogT7SiMy2v
// Component: V8IY3Apn5YGs

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsjEqVmdAbnKYc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jEqVmdAbnKYc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_inlab.module.css"; // plasmic-import: wjafXWEvDytFogT7SiMy2v/projectcss
import sty from "./PlasmicPatientCard.module.css"; // plasmic-import: V8IY3Apn5YGs/css

createPlasmicElementProxy;

export type PlasmicPatientCard__VariantMembers = {};
export type PlasmicPatientCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicPatientCard__VariantsArgs;
export const PlasmicPatientCard__VariantProps = new Array<VariantPropType>();

export type PlasmicPatientCard__ArgsType = {
  currentItem?: any;
};
type ArgPropType = keyof PlasmicPatientCard__ArgsType;
export const PlasmicPatientCard__ArgProps = new Array<ArgPropType>(
  "currentItem"
);

export type PlasmicPatientCard__OverridesType = {
  root?: p.Flex<"div">;
  dataLastUpdate?: p.Flex<"div">;
  patientFirstLastName?: p.Flex<"div">;
  patientRoomBed?: p.Flex<"div">;
  patientService?: p.Flex<"div">;
  patientButtons?: p.Flex<"div">;
  patientProfile?: p.Flex<typeof p.PlasmicImg>;
  radiologyReport?: p.Flex<typeof p.PlasmicImg>;
  laboratory?: p.Flex<typeof p.PlasmicImg>;
};

export interface DefaultPatientCardProps {
  currentItem?: any;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPatientCard__RenderFunc(props: {
  variants: PlasmicPatientCard__VariantsArgs;
  args: PlasmicPatientCard__ArgsType;
  overrides: PlasmicPatientCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjEqVmdAbnKYc()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__pGm7U)}>
        <div className={classNames(projectcss.all, sty.freeBox___6WwTq)}>
          <div
            data-plasmic-name={"dataLastUpdate"}
            data-plasmic-override={overrides.dataLastUpdate}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.dataLastUpdate
            )}
          >
            {"Enter some text"}
          </div>
          <div
            data-plasmic-name={"patientFirstLastName"}
            data-plasmic-override={overrides.patientFirstLastName}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.patientFirstLastName
            )}
          >
            {hasVariant(globalVariants, "screen", "mobileFirst") ? (
              <React.Fragment>
                {(() => {
                  try {
                    return (
                      $props.currentItem.first_name +
                      " " +
                      $props.currentItem.last_name
                    );
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            ) : (
              "Enter some text"
            )}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__yUu9N)}>
          <div
            data-plasmic-name={"patientRoomBed"}
            data-plasmic-override={overrides.patientRoomBed}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.patientRoomBed
            )}
          >
            {hasVariant(globalVariants, "screen", "mobileFirst") ? (
              <React.Fragment>
                {(() => {
                  try {
                    return (
                      $props.currentItem.room + " " + $props.currentItem.bed
                    );
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            ) : (
              "Enter some text"
            )}
          </div>
          <div
            data-plasmic-name={"patientService"}
            data-plasmic-override={overrides.patientService}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.patientService
            )}
          >
            {hasVariant(globalVariants, "screen", "mobileFirst") ? (
              <React.Fragment>
                {(() => {
                  try {
                    return $props.currentItem.service_name;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            ) : (
              "Enter some text"
            )}
          </div>
        </div>
        <div
          data-plasmic-name={"patientButtons"}
          data-plasmic-override={overrides.patientButtons}
          className={classNames(projectcss.all, sty.patientButtons)}
        >
          <p.PlasmicImg
            data-plasmic-name={"patientProfile"}
            data-plasmic-override={overrides.patientProfile}
            alt={""}
            className={classNames(sty.patientProfile)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={
              hasVariant(globalVariants, "screen", "mobileFirst")
                ? "15px"
                : "auto"
            }
            loading={"lazy"}
            onClick={async event => {
              const $steps = {};

              $steps["goToPatientProfile"] = true
                ? (() => {
                    const actionArgs = {
                      destination: `/patient_profile/${(() => {
                        try {
                          return $props.currentItem.code;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}/${(() => {
                        try {
                          return (
                            $props.currentItem.first_name +
                            " " +
                            $props.currentItem.last_name
                          );
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}`
                    };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToPatientProfile"] != null &&
                typeof $steps["goToPatientProfile"] === "object" &&
                typeof $steps["goToPatientProfile"].then === "function"
              ) {
                $steps["goToPatientProfile"] = await $steps[
                  "goToPatientProfile"
                ];
              }
            }}
            src={
              hasVariant(globalVariants, "screen", "mobileFirst")
                ? {
                    src: "/plasmic/inlab/images/group2063.svg",
                    fullWidth: 18.77,
                    fullHeight: 20.34,
                    aspectRatio: 0.904762
                  }
                : undefined
            }
          />

          <p.PlasmicImg
            data-plasmic-name={"radiologyReport"}
            data-plasmic-override={overrides.radiologyReport}
            alt={""}
            className={classNames(sty.radiologyReport)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={
              hasVariant(globalVariants, "screen", "mobileFirst")
                ? "20px"
                : "auto"
            }
            loading={"lazy"}
            onClick={async event => {
              const $steps = {};

              $steps["goToRadiologyReport1"] = true
                ? (() => {
                    const actionArgs = {
                      destination: `/imaging_report/${(() => {
                        try {
                          return $props.currentItem.code;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}/${(() => {
                        try {
                          return (
                            $props.currentItem.first_name +
                            " " +
                            $props.currentItem.last_name
                          );
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}`
                    };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToRadiologyReport1"] != null &&
                typeof $steps["goToRadiologyReport1"] === "object" &&
                typeof $steps["goToRadiologyReport1"].then === "function"
              ) {
                $steps["goToRadiologyReport1"] = await $steps[
                  "goToRadiologyReport1"
                ];
              }
            }}
            src={
              hasVariant(globalVariants, "screen", "mobileFirst")
                ? {
                    src: "/plasmic/inlab/images/group376.svg",
                    fullWidth: 19.424,
                    fullHeight: 19.98,
                    aspectRatio: 1
                  }
                : undefined
            }
          />

          <p.PlasmicImg
            data-plasmic-name={"laboratory"}
            data-plasmic-override={overrides.laboratory}
            alt={""}
            className={classNames(sty.laboratory)}
            displayHeight={
              hasVariant(globalVariants, "screen", "mobileFirst")
                ? "auto"
                : "auto"
            }
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={
              hasVariant(globalVariants, "screen", "mobileFirst")
                ? "15px"
                : "auto"
            }
            loading={"lazy"}
            onClick={async event => {
              const $steps = {};

              $steps["goToLaboratoryData"] = true
                ? (() => {
                    const actionArgs = {
                      destination: `/laboratory_data/${(() => {
                        try {
                          return $props.currentItem.code;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}/${(() => {
                        try {
                          return (
                            $props.currentItem.first_name +
                            " " +
                            $props.currentItem.last_name
                          );
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}`
                    };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToLaboratoryData"] != null &&
                typeof $steps["goToLaboratoryData"] === "object" &&
                typeof $steps["goToLaboratoryData"].then === "function"
              ) {
                $steps["goToLaboratoryData"] = await $steps[
                  "goToLaboratoryData"
                ];
              }
            }}
            src={
              hasVariant(globalVariants, "screen", "mobileFirst")
                ? {
                    src: "/plasmic/inlab/images/group384.svg",
                    fullWidth: 14.575,
                    fullHeight: 18.692,
                    aspectRatio: 0.789474
                  }
                : undefined
            }
          />
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "dataLastUpdate",
    "patientFirstLastName",
    "patientRoomBed",
    "patientService",
    "patientButtons",
    "patientProfile",
    "radiologyReport",
    "laboratory"
  ],
  dataLastUpdate: ["dataLastUpdate"],
  patientFirstLastName: ["patientFirstLastName"],
  patientRoomBed: ["patientRoomBed"],
  patientService: ["patientService"],
  patientButtons: [
    "patientButtons",
    "patientProfile",
    "radiologyReport",
    "laboratory"
  ],
  patientProfile: ["patientProfile"],
  radiologyReport: ["radiologyReport"],
  laboratory: ["laboratory"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  dataLastUpdate: "div";
  patientFirstLastName: "div";
  patientRoomBed: "div";
  patientService: "div";
  patientButtons: "div";
  patientProfile: typeof p.PlasmicImg;
  radiologyReport: typeof p.PlasmicImg;
  laboratory: typeof p.PlasmicImg;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPatientCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPatientCard__VariantsArgs;
    args?: PlasmicPatientCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPatientCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPatientCard__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPatientCard__ArgProps,
          internalVariantPropNames: PlasmicPatientCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPatientCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPatientCard";
  } else {
    func.displayName = `PlasmicPatientCard.${nodeName}`;
  }
  return func;
}

export const PlasmicPatientCard = Object.assign(
  // Top-level PlasmicPatientCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dataLastUpdate: makeNodeComponent("dataLastUpdate"),
    patientFirstLastName: makeNodeComponent("patientFirstLastName"),
    patientRoomBed: makeNodeComponent("patientRoomBed"),
    patientService: makeNodeComponent("patientService"),
    patientButtons: makeNodeComponent("patientButtons"),
    patientProfile: makeNodeComponent("patientProfile"),
    radiologyReport: makeNodeComponent("radiologyReport"),
    laboratory: makeNodeComponent("laboratory"),

    // Metadata about props expected for PlasmicPatientCard
    internalVariantProps: PlasmicPatientCard__VariantProps,
    internalArgProps: PlasmicPatientCard__ArgProps
  }
);

export default PlasmicPatientCard;
/* prettier-ignore-end */
