// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wjafXWEvDytFogT7SiMy2v
// Component: AFB-1jxjMqDb

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import H from "../../H"; // plasmic-import: -ckcELWzdUW7/component
import { ApiFetcherComponent } from "../../../utils/ApiFetcherComponent"; // plasmic-import: kxxsrihQ2d7W/codeComponent
import Button from "../../Button"; // plasmic-import: IoZvAstVrNqa/component
import SwitchingTab from "../../SwitchingTab"; // plasmic-import: 9Hr8d57xz9H9/component
import RedirectUserToLoginPage from "../../RedirectUserToLoginPage"; // plasmic-import: 0wFpBWYaqpsM/component

import { useScreenVariants as useScreenVariantsjEqVmdAbnKYc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jEqVmdAbnKYc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_inlab.module.css"; // plasmic-import: wjafXWEvDytFogT7SiMy2v/projectcss
import sty from "./PlasmicImagingReport1.module.css"; // plasmic-import: AFB-1jxjMqDb/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: I6pxicA96WJm/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: vsUaT3pPwdP4/icon

createPlasmicElementProxy;

export type PlasmicImagingReport1__VariantMembers = {};
export type PlasmicImagingReport1__VariantsArgs = {};
type VariantPropType = keyof PlasmicImagingReport1__VariantsArgs;
export const PlasmicImagingReport1__VariantProps = new Array<VariantPropType>();

export type PlasmicImagingReport1__ArgsType = {};
type ArgPropType = keyof PlasmicImagingReport1__ArgsType;
export const PlasmicImagingReport1__ArgProps = new Array<ArgPropType>();

export type PlasmicImagingReport1__OverridesType = {
  imagingReport1?: p.Flex<"div">;
  h?: p.Flex<typeof H>;
  reports?: p.Flex<typeof ApiFetcherComponent>;
  viewPacs?: p.Flex<typeof Button>;
  text?: p.Flex<"div">;
  imagingTitle?: p.Flex<"div">;
  imagingDatetime?: p.Flex<"div">;
  imagingType?: p.Flex<"div">;
  switchingTabs?: p.Flex<"div">;
  switchingTab?: p.Flex<typeof SwitchingTab>;
  redirectUserToLoginPage?: p.Flex<typeof RedirectUserToLoginPage>;
};

export interface DefaultImagingReport1Props {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicImagingReport1__RenderFunc(props: {
  variants: PlasmicImagingReport1__VariantsArgs;
  args: PlasmicImagingReport1__ArgsType;
  overrides: PlasmicImagingReport1__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof p.useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "viewPacs.isDisabled",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjEqVmdAbnKYc()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"imagingReport1"}
        data-plasmic-override={overrides.imagingReport1}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens,
          plasmic_plasmic_rich_components_css.plasmic_tokens,
          sty.imagingReport1
        )}
      >
        <H
          data-plasmic-name={"h"}
          data-plasmic-override={overrides.h}
          className={classNames("__wab_instance", sty.h)}
        />

        <ApiFetcherComponent
          data-plasmic-name={"reports"}
          data-plasmic-override={overrides.reports}
          className={classNames("__wab_instance", sty.reports)}
          headers={{ "X-Namespace": 1 }}
          method={"GET"}
          path={`/api/v2/patient/${$ctx.params.code}/radiology_services/recent?offset=0&limit=20`}
        >
          <ph.DataCtxReader>
            {$ctx => (
              <React.Fragment>
                <Button
                  data-plasmic-name={"viewPacs"}
                  data-plasmic-override={overrides.viewPacs}
                  className={classNames("__wab_instance", sty.viewPacs)}
                  isDisabled={p.generateStateValueProp($state, [
                    "viewPacs",
                    "isDisabled"
                  ])}
                  onClick={async event => {
                    const $steps = {};

                    $steps["goToPage"] = true
                      ? (() => {
                          const actionArgs = {
                            destination: (() => {
                              try {
                                return $ctx.fetched_data.data.pacs_url;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()
                          };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToPage"] != null &&
                      typeof $steps["goToPage"] === "object" &&
                      typeof $steps["goToPage"].then === "function"
                    ) {
                      $steps["goToPage"] = await $steps["goToPage"];
                    }
                  }}
                  onIsDisabledChange={(...eventArgs) => {
                    p.generateStateOnChangeProp($state, [
                      "viewPacs",
                      "isDisabled"
                    ])(eventArgs[0]);
                  }}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___8ASag)}
                  >
                    <div
                      data-plasmic-name={"text"}
                      data-plasmic-override={overrides.text}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#FFFFFF" }}
                        >
                          {"View PACS"}
                        </span>
                      </React.Fragment>
                    </div>
                  </div>
                </Button>
                {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                  (() => {
                    try {
                      return $ctx.fetched_data.data.radiology_services;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()
                ).map((__plasmic_item_0, __plasmic_idx_0) => {
                  const currentItem = __plasmic_item_0;
                  const currentIndex = __plasmic_idx_0;
                  return (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__rkUf)}
                      key={currentIndex}
                      onClick={async event => {
                        const $steps = {};

                        $steps["goToImagingReports2"] = true
                          ? (() => {
                              const actionArgs = {
                                destination: `/patient/${(() => {
                                  try {
                                    return $ctx.params.code;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })()}/${(() => {
                                  try {
                                    return $ctx.params.patient_name;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })()}/report/detail/${(() => {
                                  try {
                                    return currentItem.report;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })()}`
                              };
                              return (({ destination }) => {
                                if (
                                  typeof destination === "string" &&
                                  destination.startsWith("#")
                                ) {
                                  document
                                    .getElementById(destination.substr(1))
                                    .scrollIntoView({ behavior: "smooth" });
                                } else {
                                  __nextRouter?.push(destination);
                                }
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["goToImagingReports2"] != null &&
                          typeof $steps["goToImagingReports2"] === "object" &&
                          typeof $steps["goToImagingReports2"].then ===
                            "function"
                        ) {
                          $steps["goToImagingReports2"] = await $steps[
                            "goToImagingReports2"
                          ];
                        }
                      }}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__zDxkb
                        )}
                      >
                        <div
                          data-plasmic-name={"imagingTitle"}
                          data-plasmic-override={overrides.imagingTitle}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.imagingTitle
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return currentItem.service_name;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        <div
                          data-plasmic-name={"imagingDatetime"}
                          data-plasmic-override={overrides.imagingDatetime}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.imagingDatetime
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return (() => {
                                  const gregorianDate = new Date(
                                    currentItem.service_datetime
                                  );
                                  const shamsiDate = new Intl.DateTimeFormat(
                                    "fa-IR"
                                  ).format(gregorianDate);
                                  const shamsiTime =
                                    gregorianDate.toLocaleTimeString("fa-IR", {
                                      hour12: false
                                    });
                                  const englishDate = shamsiDate.replace(
                                    /[۰-۹]/g,
                                    d =>
                                      String.fromCharCode(
                                        d.charCodeAt(0) - 1728
                                      )
                                  );
                                  const englishTime = shamsiTime.replace(
                                    /[۰-۹]/g,
                                    d =>
                                      String.fromCharCode(
                                        d.charCodeAt(0) - 1728
                                      )
                                  );
                                  return `${englishDate}  ${englishTime}`;
                                })();
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"imagingType"}
                        data-plasmic-override={overrides.imagingType}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.imagingType
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return currentItem.title;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                  );
                })}
              </React.Fragment>
            )}
          </ph.DataCtxReader>
        </ApiFetcherComponent>
        <div
          data-plasmic-name={"switchingTabs"}
          data-plasmic-override={overrides.switchingTabs}
          className={classNames(projectcss.all, sty.switchingTabs)}
        >
          <SwitchingTab
            data-plasmic-name={"switchingTab"}
            data-plasmic-override={overrides.switchingTab}
            className={classNames("__wab_instance", sty.switchingTab)}
          />
        </div>
        <RedirectUserToLoginPage
          data-plasmic-name={"redirectUserToLoginPage"}
          data-plasmic-override={overrides.redirectUserToLoginPage}
          className={classNames("__wab_instance", sty.redirectUserToLoginPage)}
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  imagingReport1: [
    "imagingReport1",
    "h",
    "reports",
    "viewPacs",
    "text",
    "imagingTitle",
    "imagingDatetime",
    "imagingType",
    "switchingTabs",
    "switchingTab",
    "redirectUserToLoginPage"
  ],
  h: ["h"],
  reports: [
    "reports",
    "viewPacs",
    "text",
    "imagingTitle",
    "imagingDatetime",
    "imagingType"
  ],
  viewPacs: ["viewPacs", "text"],
  text: ["text"],
  imagingTitle: ["imagingTitle"],
  imagingDatetime: ["imagingDatetime"],
  imagingType: ["imagingType"],
  switchingTabs: ["switchingTabs", "switchingTab"],
  switchingTab: ["switchingTab"],
  redirectUserToLoginPage: ["redirectUserToLoginPage"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  imagingReport1: "div";
  h: typeof H;
  reports: typeof ApiFetcherComponent;
  viewPacs: typeof Button;
  text: "div";
  imagingTitle: "div";
  imagingDatetime: "div";
  imagingType: "div";
  switchingTabs: "div";
  switchingTab: typeof SwitchingTab;
  redirectUserToLoginPage: typeof RedirectUserToLoginPage;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicImagingReport1__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicImagingReport1__VariantsArgs;
    args?: PlasmicImagingReport1__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicImagingReport1__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicImagingReport1__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicImagingReport1__ArgProps,
          internalVariantPropNames: PlasmicImagingReport1__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicImagingReport1__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "imagingReport1") {
    func.displayName = "PlasmicImagingReport1";
  } else {
    func.displayName = `PlasmicImagingReport1.${nodeName}`;
  }
  return func;
}

export const PlasmicImagingReport1 = Object.assign(
  // Top-level PlasmicImagingReport1 renders the root element
  makeNodeComponent("imagingReport1"),
  {
    // Helper components rendering sub-elements
    h: makeNodeComponent("h"),
    reports: makeNodeComponent("reports"),
    viewPacs: makeNodeComponent("viewPacs"),
    text: makeNodeComponent("text"),
    imagingTitle: makeNodeComponent("imagingTitle"),
    imagingDatetime: makeNodeComponent("imagingDatetime"),
    imagingType: makeNodeComponent("imagingType"),
    switchingTabs: makeNodeComponent("switchingTabs"),
    switchingTab: makeNodeComponent("switchingTab"),
    redirectUserToLoginPage: makeNodeComponent("redirectUserToLoginPage"),

    // Metadata about props expected for PlasmicImagingReport1
    internalVariantProps: PlasmicImagingReport1__VariantProps,
    internalArgProps: PlasmicImagingReport1__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicImagingReport1;
/* prettier-ignore-end */
