// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wjafXWEvDytFogT7SiMy2v
// Component: RHOuYiwuacpG

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: pMquA3hEaxCO/component
import Button from "../../Button"; // plasmic-import: IoZvAstVrNqa/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import { useScreenVariants as useScreenVariantsjEqVmdAbnKYc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jEqVmdAbnKYc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_inlab.module.css"; // plasmic-import: wjafXWEvDytFogT7SiMy2v/projectcss
import sty from "./PlasmicSetting.module.css"; // plasmic-import: RHOuYiwuacpG/css

import ProfileIcon from "./icons/PlasmicIcon__Profile"; // plasmic-import: -RBNimWBwZ_J/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: Pji6nZZT_lpO/icon
import Group1917Icon from "./icons/PlasmicIcon__Group1917"; // plasmic-import: ycuumst0kLdp/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: I6pxicA96WJm/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: vsUaT3pPwdP4/icon

createPlasmicElementProxy;

export type PlasmicSetting__VariantMembers = {};
export type PlasmicSetting__VariantsArgs = {};
type VariantPropType = keyof PlasmicSetting__VariantsArgs;
export const PlasmicSetting__VariantProps = new Array<VariantPropType>();

export type PlasmicSetting__ArgsType = {
  settingHeader?: React.ReactNode;
};
type ArgPropType = keyof PlasmicSetting__ArgsType;
export const PlasmicSetting__ArgProps = new Array<ArgPropType>("settingHeader");

export type PlasmicSetting__OverridesType = {
  root?: p.Flex<"div">;
  picsAndName2?: p.Flex<"div">;
  name2?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  myProfile?: p.Flex<"div">;
  myProfile2?: p.Flex<"div">;
  hospital?: p.Flex<"div">;
  hospital2?: p.Flex<"div">;
  hospital3?: p.Flex<"svg">;
  resetPassword?: p.Flex<"div">;
  resetPassword2?: p.Flex<"div">;
  resetPass?: p.Flex<"svg">;
  logout?: p.Flex<typeof Button>;
};

export interface DefaultSettingProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSetting__RenderFunc(props: {
  variants: PlasmicSetting__VariantsArgs;
  args: PlasmicSetting__ArgsType;
  overrides: PlasmicSetting__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = ph.useGlobalActions?.();

  const currentUser = p.useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjEqVmdAbnKYc()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__ttAvM)}>
            {p.renderPlasmicSlot({
              defaultContents: (
                <Header
                  className={classNames("__wab_instance", sty.header___6UrwG)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xvafE
                    )}
                  >
                    {"Setting"}
                  </div>
                </Header>
              ),
              value: args.settingHeader
            })}
            <div
              data-plasmic-name={"picsAndName2"}
              data-plasmic-override={overrides.picsAndName2}
              className={classNames(projectcss.all, sty.picsAndName2)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__mrH0L)}
              >
                <div
                  data-plasmic-name={"name2"}
                  data-plasmic-override={overrides.name2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.name2
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return (() => {
                          const output =
                            $ctx.inlab_user &&
                            $ctx.inlab_user?.user?.first_name +
                              " " +
                              $ctx.inlab_user?.user?.last_name;
                          return output !== null ? output : "undefined";
                        })();
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "Undefined";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nrO8M
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $ctx.inlab_user.user.rank.title;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "Undefined";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9Fkg4
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $ctx.inlab_user.user.username;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "Undefined";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
              </p.Stack>
              <p.PlasmicImg
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"61px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/inlab/images/image3.svg",
                  fullWidth: 150,
                  fullHeight: 150,
                  aspectRatio: 1
                }}
              />
            </div>
            <p.Stack
              as={"div"}
              data-plasmic-name={"myProfile"}
              data-plasmic-override={overrides.myProfile}
              hasGap={true}
              className={classNames(projectcss.all, sty.myProfile)}
              onClick={async event => {
                const $steps = {};

                $steps["goToUserProfile"] = true
                  ? (() => {
                      const actionArgs = { destination: `/myprofile` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToUserProfile"] != null &&
                  typeof $steps["goToUserProfile"] === "object" &&
                  typeof $steps["goToUserProfile"].then === "function"
                ) {
                  $steps["goToUserProfile"] = await $steps["goToUserProfile"];
                }
              }}
            >
              <div
                data-plasmic-name={"myProfile2"}
                data-plasmic-override={overrides.myProfile2}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.myProfile2
                )}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToMyprofile"] = true
                    ? (() => {
                        const actionArgs = { destination: `/myprofile` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToMyprofile"] != null &&
                    typeof $steps["goToMyprofile"] === "object" &&
                    typeof $steps["goToMyprofile"].then === "function"
                  ) {
                    $steps["goToMyprofile"] = await $steps["goToMyprofile"];
                  }
                }}
              >
                {"My profile"}
              </div>
              <ProfileIcon
                className={classNames(projectcss.all, sty.svg___5QIhx)}
                role={"img"}
              />
            </p.Stack>
            <p.Stack
              as={"div"}
              data-plasmic-name={"hospital"}
              data-plasmic-override={overrides.hospital}
              hasGap={true}
              className={classNames(projectcss.all, sty.hospital)}
            >
              <div
                data-plasmic-name={"hospital2"}
                data-plasmic-override={overrides.hospital2}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.hospital2
                )}
              >
                {"Hospital"}
              </div>
              <Icon3Icon
                data-plasmic-name={"hospital3"}
                data-plasmic-override={overrides.hospital3}
                className={classNames(projectcss.all, sty.hospital3)}
                role={"img"}
              />
            </p.Stack>
            <p.Stack
              as={"div"}
              data-plasmic-name={"resetPassword"}
              data-plasmic-override={overrides.resetPassword}
              hasGap={true}
              className={classNames(projectcss.all, sty.resetPassword)}
              onClick={async event => {
                const $steps = {};

                $steps[
                  "goToHttpsdocsgooglecomformsde1FaIpQlScmvuKNhINyeNxRdba6NrmsCqzl5Ncc60Hbkqa6X42KIhXgkQviewformuspsfLink"
                ] = true
                  ? (() => {
                      const actionArgs = {
                        destination:
                          "https://docs.google.com/forms/d/e/1FAIpQLScmvuKNhINyeNxRDBA6NRMSCqzl5NCC60Hbkqa6X42kIhXGKQ/viewform?usp=sf_link"
                      };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps[
                    "goToHttpsdocsgooglecomformsde1FaIpQlScmvuKNhINyeNxRdba6NrmsCqzl5Ncc60Hbkqa6X42KIhXgkQviewformuspsfLink"
                  ] != null &&
                  typeof $steps[
                    "goToHttpsdocsgooglecomformsde1FaIpQlScmvuKNhINyeNxRdba6NrmsCqzl5Ncc60Hbkqa6X42KIhXgkQviewformuspsfLink"
                  ] === "object" &&
                  typeof $steps[
                    "goToHttpsdocsgooglecomformsde1FaIpQlScmvuKNhINyeNxRdba6NrmsCqzl5Ncc60Hbkqa6X42KIhXgkQviewformuspsfLink"
                  ].then === "function"
                ) {
                  $steps[
                    "goToHttpsdocsgooglecomformsde1FaIpQlScmvuKNhINyeNxRdba6NrmsCqzl5Ncc60Hbkqa6X42KIhXgkQviewformuspsfLink"
                  ] = await $steps[
                    "goToHttpsdocsgooglecomformsde1FaIpQlScmvuKNhINyeNxRdba6NrmsCqzl5Ncc60Hbkqa6X42KIhXgkQviewformuspsfLink"
                  ];
                }
              }}
            >
              <div
                data-plasmic-name={"resetPassword2"}
                data-plasmic-override={overrides.resetPassword2}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.resetPassword2
                )}
                onClick={async event => {
                  const $steps = {};

                  $steps[
                    "goToHttpsdocsgooglecomformsde1FaIpQlScmvuKNhINyeNxRdba6NrmsCqzl5Ncc60Hbkqa6X42KIhXgkQviewformuspsfLink"
                  ] = true
                    ? (() => {
                        const actionArgs = {
                          destination:
                            "https://docs.google.com/forms/d/e/1FAIpQLScmvuKNhINyeNxRDBA6NRMSCqzl5NCC60Hbkqa6X42kIhXGKQ/viewform?usp=sf_link"
                        };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps[
                      "goToHttpsdocsgooglecomformsde1FaIpQlScmvuKNhINyeNxRdba6NrmsCqzl5Ncc60Hbkqa6X42KIhXgkQviewformuspsfLink"
                    ] != null &&
                    typeof $steps[
                      "goToHttpsdocsgooglecomformsde1FaIpQlScmvuKNhINyeNxRdba6NrmsCqzl5Ncc60Hbkqa6X42KIhXgkQviewformuspsfLink"
                    ] === "object" &&
                    typeof $steps[
                      "goToHttpsdocsgooglecomformsde1FaIpQlScmvuKNhINyeNxRdba6NrmsCqzl5Ncc60Hbkqa6X42KIhXgkQviewformuspsfLink"
                    ].then === "function"
                  ) {
                    $steps[
                      "goToHttpsdocsgooglecomformsde1FaIpQlScmvuKNhINyeNxRdba6NrmsCqzl5Ncc60Hbkqa6X42KIhXgkQviewformuspsfLink"
                    ] = await $steps[
                      "goToHttpsdocsgooglecomformsde1FaIpQlScmvuKNhINyeNxRdba6NrmsCqzl5Ncc60Hbkqa6X42KIhXgkQviewformuspsfLink"
                    ];
                  }
                }}
              >
                {"Reset password"}
              </div>
              <Group1917Icon
                data-plasmic-name={"resetPass"}
                data-plasmic-override={overrides.resetPass}
                className={classNames(projectcss.all, sty.resetPass)}
                role={"img"}
              />
            </p.Stack>
            <Button
              data-plasmic-name={"logout"}
              data-plasmic-override={overrides.logout}
              className={classNames("__wab_instance", sty.logout)}
              onClick={async event => {
                const $steps = {};

                $steps["logOut"] = true
                  ? (() => {
                      const actionArgs = { args: [] };
                      return $globalActions["AuthGlobalContext.logout"]?.apply(
                        null,
                        [...actionArgs.args]
                      );
                    })()
                  : undefined;
                if (
                  $steps["logOut"] != null &&
                  typeof $steps["logOut"] === "object" &&
                  typeof $steps["logOut"].then === "function"
                ) {
                  $steps["logOut"] = await $steps["logOut"];
                }

                $steps["goToInlabLogin"] = $steps.logOut
                  ? (() => {
                      const actionArgs = { destination: `/` };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToInlabLogin"] != null &&
                  typeof $steps["goToInlabLogin"] === "object" &&
                  typeof $steps["goToInlabLogin"].then === "function"
                ) {
                  $steps["goToInlabLogin"] = await $steps["goToInlabLogin"];
                }
              }}
              startIcon={
                <ChecksvgIcon
                  className={classNames(projectcss.all, sty.svg__fLi6W)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zjr24
                )}
              >
                {"Log Out"}
              </div>
            </Button>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "picsAndName2",
    "name2",
    "img",
    "myProfile",
    "myProfile2",
    "hospital",
    "hospital2",
    "hospital3",
    "resetPassword",
    "resetPassword2",
    "resetPass",
    "logout"
  ],
  picsAndName2: ["picsAndName2", "name2", "img"],
  name2: ["name2"],
  img: ["img"],
  myProfile: ["myProfile", "myProfile2"],
  myProfile2: ["myProfile2"],
  hospital: ["hospital", "hospital2", "hospital3"],
  hospital2: ["hospital2"],
  hospital3: ["hospital3"],
  resetPassword: ["resetPassword", "resetPassword2", "resetPass"],
  resetPassword2: ["resetPassword2"],
  resetPass: ["resetPass"],
  logout: ["logout"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  picsAndName2: "div";
  name2: "div";
  img: typeof p.PlasmicImg;
  myProfile: "div";
  myProfile2: "div";
  hospital: "div";
  hospital2: "div";
  hospital3: "svg";
  resetPassword: "div";
  resetPassword2: "div";
  resetPass: "svg";
  logout: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSetting__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSetting__VariantsArgs;
    args?: PlasmicSetting__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSetting__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSetting__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSetting__ArgProps,
          internalVariantPropNames: PlasmicSetting__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSetting__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSetting";
  } else {
    func.displayName = `PlasmicSetting.${nodeName}`;
  }
  return func;
}

export const PlasmicSetting = Object.assign(
  // Top-level PlasmicSetting renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    picsAndName2: makeNodeComponent("picsAndName2"),
    name2: makeNodeComponent("name2"),
    img: makeNodeComponent("img"),
    myProfile: makeNodeComponent("myProfile"),
    myProfile2: makeNodeComponent("myProfile2"),
    hospital: makeNodeComponent("hospital"),
    hospital2: makeNodeComponent("hospital2"),
    hospital3: makeNodeComponent("hospital3"),
    resetPassword: makeNodeComponent("resetPassword"),
    resetPassword2: makeNodeComponent("resetPassword2"),
    resetPass: makeNodeComponent("resetPass"),
    logout: makeNodeComponent("logout"),

    // Metadata about props expected for PlasmicSetting
    internalVariantProps: PlasmicSetting__VariantProps,
    internalArgProps: PlasmicSetting__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSetting;
/* prettier-ignore-end */
