// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wjafXWEvDytFogT7SiMy2v
// Component: Ev8txsbuZl9W

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import RedirectToInlabLogin from "../../RedirectToInlabLogin"; // plasmic-import: dnRUnqur1vWa/component
import RedirectToNamespaceSelection from "../../RedirectToNamespaceSelection"; // plasmic-import: rhyWwtv3sPGn/component
import { ApiFetcherComponent } from "../../../utils/ApiFetcherComponent"; // plasmic-import: kxxsrihQ2d7W/codeComponent
import Button from "../../Button"; // plasmic-import: IoZvAstVrNqa/component
import SwitchingTab from "../../SwitchingTab"; // plasmic-import: 9Hr8d57xz9H9/component
import BookmarkIcon from "../../BookmarkIcon"; // plasmic-import: PK_hwsu90gKT/component

import { useScreenVariants as useScreenVariantsjEqVmdAbnKYc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jEqVmdAbnKYc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: wjafXWEvDytFogT7SiMy2v/projectcss
import sty from "./PlasmicPatientProfile.module.css"; // plasmic-import: Ev8txsbuZl9W/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: I6pxicA96WJm/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: vsUaT3pPwdP4/icon

createPlasmicElementProxy;

export type PlasmicPatientProfile__VariantMembers = {
  bookmarkedPatient: "bookmarkedPatient";
};
export type PlasmicPatientProfile__VariantsArgs = {
  bookmarkedPatient?: SingleBooleanChoiceArg<"bookmarkedPatient">;
};
type VariantPropType = keyof PlasmicPatientProfile__VariantsArgs;
export const PlasmicPatientProfile__VariantProps = new Array<VariantPropType>(
  "bookmarkedPatient"
);

export type PlasmicPatientProfile__ArgsType = {};
type ArgPropType = keyof PlasmicPatientProfile__ArgsType;
export const PlasmicPatientProfile__ArgProps = new Array<ArgPropType>();

export type PlasmicPatientProfile__OverridesType = {
  patientProfile2?: Flex__<"div">;
  redirectToInlabLogin?: Flex__<typeof RedirectToInlabLogin>;
  redirectToNamespaceSelection?: Flex__<typeof RedirectToNamespaceSelection>;
  header?: Flex__<"div">;
  patientProfile?: Flex__<typeof ApiFetcherComponent>;
  patientData?: Flex__<"div">;
  patientProfileBox?: Flex__<"div">;
  nationalIdAdmissionTimeNoPacs?: Flex__<"div">;
  nationalId?: Flex__<"div">;
  admissionDate?: Flex__<"div">;
  patientNo?: Flex__<"div">;
  pacsNumber?: Flex__<"div">;
  pacsNumber2?: Flex__<"div">;
  nameServiceWardBed?: Flex__<"div">;
  patientName2?: Flex__<"div">;
  patientService?: Flex__<"div">;
  patientWard?: Flex__<"div">;
  patientRoomBed?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  patientStatus?: Flex__<"div">;
  وضعیتبیمار?: Flex__<"div">;
  bioArcPrescription?: Flex__<typeof Button>;
  switchingTabs?: Flex__<"div">;
  switchingTab?: Flex__<typeof SwitchingTab>;
  homepage?: Flex__<typeof PlasmicImg__>;
  patientProfile5?: Flex__<typeof PlasmicImg__>;
  radiologyReport?: Flex__<typeof PlasmicImg__>;
  laboratory?: Flex__<typeof PlasmicImg__>;
  bookmarkIcon?: Flex__<typeof BookmarkIcon>;
};

export interface DefaultPatientProfileProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPatientProfile__RenderFunc(props: {
  variants: PlasmicPatientProfile__VariantsArgs;
  args: PlasmicPatientProfile__ArgsType;
  overrides: PlasmicPatientProfile__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "bioArcPrescription.isDisabled",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "bioArcPrescription.selected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "bioArcPrescription.deselected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "bioArcPrescription.sortDeselected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "bioArcPrescription.sortSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "bookmarkedPatient",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          $props.bookmarkedPatient
      },
      {
        path: "bookmarkIcon.selected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $ctx.params.bookmarked === "true" ? true : false;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return false;
              }
              throw e;
            }
          })()
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjEqVmdAbnKYc()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"patientProfile2"}
          data-plasmic-override={overrides.patientProfile2}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.patientProfile2
          )}
        >
          <RedirectToInlabLogin
            data-plasmic-name={"redirectToInlabLogin"}
            data-plasmic-override={overrides.redirectToInlabLogin}
            className={classNames("__wab_instance", sty.redirectToInlabLogin)}
          />

          <RedirectToNamespaceSelection
            data-plasmic-name={"redirectToNamespaceSelection"}
            data-plasmic-override={overrides.redirectToNamespaceSelection}
            className={classNames(
              "__wab_instance",
              sty.redirectToNamespaceSelection
            )}
          />

          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jAw6U
              )}
            >
              {
                "\u0627\u0637\u0644\u0627\u0639\u0627\u062a \u0628\u06cc\u0645\u0627\u0631 "
              }
            </div>
          </div>
          <ApiFetcherComponent
            data-plasmic-name={"patientProfile"}
            data-plasmic-override={overrides.patientProfile}
            className={classNames("__wab_instance", sty.patientProfile)}
            delay={0}
            headers={(() => {
              try {
                return {
                  "X-Namespace": localStorage.getItem("inlab_user_namespace_id")
                };
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
            method={"GET"}
            path={`/api/v2/patient/${$ctx.params.code}`}
            ref={ref => {
              $refs["patientProfile"] = ref;
            }}
          >
            <DataCtxReader__>
              {$ctx => (
                <React.Fragment>
                  {$ctx.fetched_data.loading == true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3Uzzq
                      )}
                    >
                      {
                        "\u0644\u0637\u0641\u0627 \u0645\u0646\u062a\u0638\u0631 \u0628\u0645\u0627\u0646\u06cc\u062f"
                      }
                    </div>
                  ) : null}
                  {(() => {
                    try {
                      return $ctx.fetched_data.loading == false;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return true;
                      }
                      throw e;
                    }
                  })() ? (
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"patientData"}
                      data-plasmic-override={overrides.patientData}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.patientData)}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"patientProfileBox"}
                        data-plasmic-override={overrides.patientProfileBox}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.patientProfileBox
                        )}
                      >
                        <div
                          data-plasmic-name={"nationalIdAdmissionTimeNoPacs"}
                          data-plasmic-override={
                            overrides.nationalIdAdmissionTimeNoPacs
                          }
                          className={classNames(
                            projectcss.all,
                            sty.nationalIdAdmissionTimeNoPacs
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__aZwd
                            )}
                          >
                            {"National ID"}
                          </div>
                          <div
                            data-plasmic-name={"nationalId"}
                            data-plasmic-override={overrides.nationalId}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.nationalId
                            )}
                          >
                            <React.Fragment>
                              {$ctx.fetched_data.loading == false &&
                                $ctx.fetched_data.data.national_id}
                            </React.Fragment>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___3OiCc
                            )}
                          >
                            {"Admission "}
                          </div>
                          <div
                            data-plasmic-name={"admissionDate"}
                            data-plasmic-override={overrides.admissionDate}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.admissionDate
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                const gregorianDate = new Date(
                                  $ctx.fetched_data.data.admission_datetime
                                );
                                const shamsiDate = new Intl.DateTimeFormat(
                                  "fa-IR"
                                ).format(gregorianDate);
                                const shamsiTime =
                                  gregorianDate.toLocaleTimeString("fa-IR", {
                                    hour12: false
                                  });
                                const englishDate = shamsiDate.replace(
                                  /[۰-۹]/g,
                                  d =>
                                    String.fromCharCode(d.charCodeAt(0) - 1728)
                                );
                                const englishTime = shamsiTime
                                  .replace(/[۰-۹]/g, d =>
                                    String.fromCharCode(d.charCodeAt(0) - 1728)
                                  )
                                  .split(":")
                                  .slice(0, 2)
                                  .join(":");
                                return `${englishDate}-${englishTime}`;
                              })()}
                            </React.Fragment>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___17Gib
                            )}
                          >
                            {"No"}
                          </div>
                          <div
                            data-plasmic-name={"patientNo"}
                            data-plasmic-override={overrides.patientNo}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.patientNo
                            )}
                          >
                            <React.Fragment>
                              {$ctx.fetched_data.data.profile_id}
                            </React.Fragment>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zzbJi
                            )}
                          >
                            {"PACS"}
                          </div>
                          <div
                            data-plasmic-name={"pacsNumber"}
                            data-plasmic-override={overrides.pacsNumber}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.pacsNumber
                            )}
                          >
                            <React.Fragment>
                              {$ctx.fetched_data.data.admission_id}
                            </React.Fragment>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___4ElHr
                            )}
                          >
                            {"Phone Number"}
                          </div>
                          <div
                            data-plasmic-name={"pacsNumber2"}
                            data-plasmic-override={overrides.pacsNumber2}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.pacsNumber2
                            )}
                          >
                            <React.Fragment>
                              {$ctx.fetched_data.data.phone_number_1}
                            </React.Fragment>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"nameServiceWardBed"}
                          data-plasmic-override={overrides.nameServiceWardBed}
                          className={classNames(
                            projectcss.all,
                            sty.nameServiceWardBed
                          )}
                        >
                          <div
                            data-plasmic-name={"patientName2"}
                            data-plasmic-override={overrides.patientName2}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.patientName2
                            )}
                            dir={"rtl"}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return (() => {
                                    const dob = new Date(
                                      $ctx.fetched_data.data.dob
                                    );
                                    const ageDiffMs =
                                      Date.now() - dob.getTime();
                                    const ageDate = new Date(ageDiffMs);
                                    const ageYears = Math.abs(
                                      ageDate.getUTCFullYear() - 1970
                                    );
                                    const fullName = `${$ctx.fetched_data.data.first_name} ${$ctx.fetched_data.data.last_name}`;
                                    if (ageYears < 1) {
                                      const ageMonths = ageDate.getUTCMonth();
                                      return `${fullName} ${ageMonths} months ${
                                        $ctx.fetched_data.data.gender === "F"
                                          ? " ♀️"
                                          : $ctx.fetched_data.data.gender ===
                                            "M"
                                          ? " ♂️"
                                          : ""
                                      }`;
                                    } else {
                                      return `${fullName} ${ageYears}${
                                        $ctx.fetched_data.data.gender === "F"
                                          ? " ♀️"
                                          : $ctx.fetched_data.data.gender ===
                                            "M"
                                          ? " ♂️"
                                          : ""
                                      }`;
                                    }
                                  })();
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qdLuE
                            )}
                          >
                            {"service "}
                          </div>
                          <div
                            data-plasmic-name={"patientService"}
                            data-plasmic-override={overrides.patientService}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.patientService
                            )}
                          >
                            <React.Fragment>
                              {$ctx.fetched_data.data.primary_service.name}
                            </React.Fragment>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gsJjX
                            )}
                          >
                            {"Ward"}
                          </div>
                          <div
                            data-plasmic-name={"patientWard"}
                            data-plasmic-override={overrides.patientWard}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.patientWard
                            )}
                          >
                            <React.Fragment>
                              {$ctx.fetched_data.data.ward.name}
                            </React.Fragment>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qdn2
                            )}
                          >
                            {"Bed"}
                          </div>
                          <div
                            data-plasmic-name={"patientRoomBed"}
                            data-plasmic-override={overrides.patientRoomBed}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.patientRoomBed
                            )}
                          >
                            <React.Fragment>
                              {$ctx.fetched_data.data.room +
                                " - " +
                                $ctx.fetched_data.data.bed}
                            </React.Fragment>
                          </div>
                        </div>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"freeBox"}
                        data-plasmic-override={overrides.freeBox}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.freeBox)}
                      >
                        <div
                          data-plasmic-name={"patientStatus"}
                          data-plasmic-override={overrides.patientStatus}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.patientStatus
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $ctx.fetched_data.data.dismissed
                                  ? "ترخیص"
                                  : "بستری";
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "\u062a\u0631\u062e\u06cc\u0635";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        <div
                          data-plasmic-name={
                            "\u0648\u0636\u0639\u06cc\u062a\u0628\u06cc\u0645\u0627\u0631"
                          }
                          data-plasmic-override={overrides.وضعیتبیمار}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.وضعیتبیمار
                          )}
                        >
                          {
                            "\u0648\u0636\u0639\u06cc\u062a \u0628\u06cc\u0645\u0627\u0631"
                          }
                        </div>
                      </Stack__>
                      <Button
                        data-plasmic-name={"bioArcPrescription"}
                        data-plasmic-override={overrides.bioArcPrescription}
                        className={classNames(
                          "__wab_instance",
                          sty.bioArcPrescription
                        )}
                        color={"blue"}
                        deselected={generateStateValueProp($state, [
                          "bioArcPrescription",
                          "deselected"
                        ])}
                        isDisabled={generateStateValueProp($state, [
                          "bioArcPrescription",
                          "isDisabled"
                        ])}
                        onClick={async event => {
                          const $steps = {};

                          $steps["goToPage"] = true
                            ? (() => {
                                const actionArgs = {};
                                return (({ destination }) => {
                                  if (
                                    typeof destination === "string" &&
                                    destination.startsWith("#")
                                  ) {
                                    document
                                      .getElementById(destination.substr(1))
                                      .scrollIntoView({ behavior: "smooth" });
                                  } else {
                                    __nextRouter?.push(destination);
                                  }
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["goToPage"] != null &&
                            typeof $steps["goToPage"] === "object" &&
                            typeof $steps["goToPage"].then === "function"
                          ) {
                            $steps["goToPage"] = await $steps["goToPage"];
                          }
                        }}
                        onDeselectedChange={(...eventArgs) => {
                          generateStateOnChangeProp($state, [
                            "bioArcPrescription",
                            "deselected"
                          ])(eventArgs[0]);
                        }}
                        onIsDisabledChange={(...eventArgs) => {
                          generateStateOnChangeProp($state, [
                            "bioArcPrescription",
                            "isDisabled"
                          ])(eventArgs[0]);
                        }}
                        onSelectedChange={(...eventArgs) => {
                          generateStateOnChangeProp($state, [
                            "bioArcPrescription",
                            "selected"
                          ])(eventArgs[0]);
                        }}
                        onSortDeselectedChange={(...eventArgs) => {
                          generateStateOnChangeProp($state, [
                            "bioArcPrescription",
                            "sortDeselected"
                          ])(eventArgs[0]);
                        }}
                        onSortSelectedChange={(...eventArgs) => {
                          generateStateOnChangeProp($state, [
                            "bioArcPrescription",
                            "sortSelected"
                          ])(eventArgs[0]);
                        }}
                        selected={generateStateValueProp($state, [
                          "bioArcPrescription",
                          "selected"
                        ])}
                        sortDeselected={generateStateValueProp($state, [
                          "bioArcPrescription",
                          "sortDeselected"
                        ])}
                        sortSelected={generateStateValueProp($state, [
                          "bioArcPrescription",
                          "sortSelected"
                        ])}
                      >
                        {
                          "\u0646\u0633\u062e\u0647 \u0646\u0648\u06cc\u0633\u06cc \u0628\u0627 \u0628\u06cc\u0648\u0622\u0631\u06a9 "
                        }
                      </Button>
                    </Stack__>
                  ) : null}
                </React.Fragment>
              )}
            </DataCtxReader__>
          </ApiFetcherComponent>
          <div
            data-plasmic-name={"switchingTabs"}
            data-plasmic-override={overrides.switchingTabs}
            className={classNames(projectcss.all, sty.switchingTabs)}
          >
            <SwitchingTab
              data-plasmic-name={"switchingTab"}
              data-plasmic-override={overrides.switchingTab}
              className={classNames("__wab_instance", sty.switchingTab)}
            >
              <PlasmicImg__
                data-plasmic-name={"homepage"}
                data-plasmic-override={overrides.homepage}
                alt={""}
                className={classNames(sty.homepage)}
                displayHeight={"25px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"25%"}
                loading={"lazy"}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToHomepage"] = true
                    ? (() => {
                        const actionArgs = { destination: `/patients` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToHomepage"] != null &&
                    typeof $steps["goToHomepage"] === "object" &&
                    typeof $steps["goToHomepage"].then === "function"
                  ) {
                    $steps["goToHomepage"] = await $steps["goToHomepage"];
                  }
                }}
                src={{
                  src: "/new_inlab/plasmic/inlab/images/icons8Home1Svg.svg",
                  fullWidth: 150,
                  fullHeight: 150,
                  aspectRatio: 1
                }}
              />

              <PlasmicImg__
                data-plasmic-name={"patientProfile5"}
                data-plasmic-override={overrides.patientProfile5}
                alt={""}
                className={classNames(sty.patientProfile5)}
                displayHeight={"25px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"25%"}
                loading={"lazy"}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToPatientProfile"] = true
                    ? (() => {
                        const actionArgs = {
                          destination: `/patient/${(() => {
                            try {
                              return $ctx.params.code;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}/profile/${(() => {
                            try {
                              return $ctx.params.adm_id;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}`
                        };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToPatientProfile"] != null &&
                    typeof $steps["goToPatientProfile"] === "object" &&
                    typeof $steps["goToPatientProfile"].then === "function"
                  ) {
                    $steps["goToPatientProfile"] = await $steps[
                      "goToPatientProfile"
                    ];
                  }
                }}
                src={{
                  src: "/new_inlab/plasmic/inlab/images/group2063.svg",
                  fullWidth: 18.77,
                  fullHeight: 20.34,
                  aspectRatio: 0.904762
                }}
              />

              <PlasmicImg__
                data-plasmic-name={"radiologyReport"}
                data-plasmic-override={overrides.radiologyReport}
                alt={""}
                className={classNames(sty.radiologyReport)}
                displayHeight={"25px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"25%"}
                loading={"lazy"}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToImagingReport1"] = true
                    ? (() => {
                        const actionArgs = {
                          destination: `/patient/${(() => {
                            try {
                              return $ctx.params.code;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}/report/list/${(() => {
                            try {
                              return $ctx.params.adm_id;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}`
                        };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToImagingReport1"] != null &&
                    typeof $steps["goToImagingReport1"] === "object" &&
                    typeof $steps["goToImagingReport1"].then === "function"
                  ) {
                    $steps["goToImagingReport1"] = await $steps[
                      "goToImagingReport1"
                    ];
                  }
                }}
                src={{
                  src: "/new_inlab/plasmic/inlab/images/group376.svg",
                  fullWidth: 19.424,
                  fullHeight: 19.98,
                  aspectRatio: 1
                }}
              />

              <PlasmicImg__
                data-plasmic-name={"laboratory"}
                data-plasmic-override={overrides.laboratory}
                alt={""}
                className={classNames(sty.laboratory)}
                displayHeight={"25px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"25%"}
                loading={"lazy"}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToLaboratoryData"] = true
                    ? (() => {
                        const actionArgs = {
                          destination: `/patient/${(() => {
                            try {
                              return $ctx.params.code;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}/lab/${(() => {
                            try {
                              return $ctx.params.adm_id;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}`
                        };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToLaboratoryData"] != null &&
                    typeof $steps["goToLaboratoryData"] === "object" &&
                    typeof $steps["goToLaboratoryData"].then === "function"
                  ) {
                    $steps["goToLaboratoryData"] = await $steps[
                      "goToLaboratoryData"
                    ];
                  }
                }}
                src={{
                  src: "/new_inlab/plasmic/inlab/images/group384.svg",
                  fullWidth: 14.575,
                  fullHeight: 18.692,
                  aspectRatio: 0.789474
                }}
              />

              {false
                ? (() => {
                    const child$Props = {
                      bookmarked: undefined,
                      className: classNames("__wab_instance", sty.bookmarkIcon),
                      onSelectedChange: generateStateOnChangeProp($state, [
                        "bookmarkIcon",
                        "selected"
                      ]),
                      patientId: (() => {
                        try {
                          return $ctx.params.code;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })(),
                      selected: generateStateValueProp($state, [
                        "bookmarkIcon",
                        "selected"
                      ]),
                      trigerReload: async () => {
                        const $steps = {};

                        $steps["updateBookmarkedPatient"] = true
                          ? (() => {
                              const actionArgs = {
                                vgroup: "bookmarkedPatient",
                                operation: 2,
                                value: "bookmarkedPatient"
                              };
                              return (({ vgroup, value }) => {
                                if (typeof value === "string") {
                                  value = [value];
                                }

                                const oldValue = $stateGet($state, vgroup);
                                $stateSet($state, vgroup, !oldValue);
                                return !oldValue;
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["updateBookmarkedPatient"] != null &&
                          typeof $steps["updateBookmarkedPatient"] ===
                            "object" &&
                          typeof $steps["updateBookmarkedPatient"].then ===
                            "function"
                        ) {
                          $steps["updateBookmarkedPatient"] = await $steps[
                            "updateBookmarkedPatient"
                          ];
                        }
                      }
                    };

                    initializePlasmicStates(
                      $state,
                      [
                        {
                          name: "bookmarkIcon.selected",
                          initFunc: ({ $props, $state, $queries }) =>
                            (() => {
                              try {
                                return $ctx.params.bookmarked === "true"
                                  ? true
                                  : false;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return false;
                                }
                                throw e;
                              }
                            })()
                        }
                      ],
                      []
                    );
                    return (
                      <BookmarkIcon
                        data-plasmic-name={"bookmarkIcon"}
                        data-plasmic-override={overrides.bookmarkIcon}
                        {...child$Props}
                      />
                    );
                  })()
                : null}
            </SwitchingTab>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  patientProfile2: [
    "patientProfile2",
    "redirectToInlabLogin",
    "redirectToNamespaceSelection",
    "header",
    "patientProfile",
    "patientData",
    "patientProfileBox",
    "nationalIdAdmissionTimeNoPacs",
    "nationalId",
    "admissionDate",
    "patientNo",
    "pacsNumber",
    "pacsNumber2",
    "nameServiceWardBed",
    "patientName2",
    "patientService",
    "patientWard",
    "patientRoomBed",
    "freeBox",
    "patientStatus",
    "\u0648\u0636\u0639\u06cc\u062a\u0628\u06cc\u0645\u0627\u0631",
    "bioArcPrescription",
    "switchingTabs",
    "switchingTab",
    "homepage",
    "patientProfile5",
    "radiologyReport",
    "laboratory",
    "bookmarkIcon"
  ],
  redirectToInlabLogin: ["redirectToInlabLogin"],
  redirectToNamespaceSelection: ["redirectToNamespaceSelection"],
  header: ["header"],
  patientProfile: [
    "patientProfile",
    "patientData",
    "patientProfileBox",
    "nationalIdAdmissionTimeNoPacs",
    "nationalId",
    "admissionDate",
    "patientNo",
    "pacsNumber",
    "pacsNumber2",
    "nameServiceWardBed",
    "patientName2",
    "patientService",
    "patientWard",
    "patientRoomBed",
    "freeBox",
    "patientStatus",
    "\u0648\u0636\u0639\u06cc\u062a\u0628\u06cc\u0645\u0627\u0631",
    "bioArcPrescription"
  ],
  patientData: [
    "patientData",
    "patientProfileBox",
    "nationalIdAdmissionTimeNoPacs",
    "nationalId",
    "admissionDate",
    "patientNo",
    "pacsNumber",
    "pacsNumber2",
    "nameServiceWardBed",
    "patientName2",
    "patientService",
    "patientWard",
    "patientRoomBed",
    "freeBox",
    "patientStatus",
    "\u0648\u0636\u0639\u06cc\u062a\u0628\u06cc\u0645\u0627\u0631",
    "bioArcPrescription"
  ],
  patientProfileBox: [
    "patientProfileBox",
    "nationalIdAdmissionTimeNoPacs",
    "nationalId",
    "admissionDate",
    "patientNo",
    "pacsNumber",
    "pacsNumber2",
    "nameServiceWardBed",
    "patientName2",
    "patientService",
    "patientWard",
    "patientRoomBed"
  ],
  nationalIdAdmissionTimeNoPacs: [
    "nationalIdAdmissionTimeNoPacs",
    "nationalId",
    "admissionDate",
    "patientNo",
    "pacsNumber",
    "pacsNumber2"
  ],
  nationalId: ["nationalId"],
  admissionDate: ["admissionDate"],
  patientNo: ["patientNo"],
  pacsNumber: ["pacsNumber"],
  pacsNumber2: ["pacsNumber2"],
  nameServiceWardBed: [
    "nameServiceWardBed",
    "patientName2",
    "patientService",
    "patientWard",
    "patientRoomBed"
  ],
  patientName2: ["patientName2"],
  patientService: ["patientService"],
  patientWard: ["patientWard"],
  patientRoomBed: ["patientRoomBed"],
  freeBox: [
    "freeBox",
    "patientStatus",
    "\u0648\u0636\u0639\u06cc\u062a\u0628\u06cc\u0645\u0627\u0631"
  ],
  patientStatus: ["patientStatus"],
  وضعیتبیمار: ["\u0648\u0636\u0639\u06cc\u062a\u0628\u06cc\u0645\u0627\u0631"],
  bioArcPrescription: ["bioArcPrescription"],
  switchingTabs: [
    "switchingTabs",
    "switchingTab",
    "homepage",
    "patientProfile5",
    "radiologyReport",
    "laboratory",
    "bookmarkIcon"
  ],
  switchingTab: [
    "switchingTab",
    "homepage",
    "patientProfile5",
    "radiologyReport",
    "laboratory",
    "bookmarkIcon"
  ],
  homepage: ["homepage"],
  patientProfile5: ["patientProfile5"],
  radiologyReport: ["radiologyReport"],
  laboratory: ["laboratory"],
  bookmarkIcon: ["bookmarkIcon"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  patientProfile2: "div";
  redirectToInlabLogin: typeof RedirectToInlabLogin;
  redirectToNamespaceSelection: typeof RedirectToNamespaceSelection;
  header: "div";
  patientProfile: typeof ApiFetcherComponent;
  patientData: "div";
  patientProfileBox: "div";
  nationalIdAdmissionTimeNoPacs: "div";
  nationalId: "div";
  admissionDate: "div";
  patientNo: "div";
  pacsNumber: "div";
  pacsNumber2: "div";
  nameServiceWardBed: "div";
  patientName2: "div";
  patientService: "div";
  patientWard: "div";
  patientRoomBed: "div";
  freeBox: "div";
  patientStatus: "div";
  وضعیتبیمار: "div";
  bioArcPrescription: typeof Button;
  switchingTabs: "div";
  switchingTab: typeof SwitchingTab;
  homepage: typeof PlasmicImg__;
  patientProfile5: typeof PlasmicImg__;
  radiologyReport: typeof PlasmicImg__;
  laboratory: typeof PlasmicImg__;
  bookmarkIcon: typeof BookmarkIcon;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPatientProfile__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPatientProfile__VariantsArgs;
    args?: PlasmicPatientProfile__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPatientProfile__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPatientProfile__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPatientProfile__ArgProps,
          internalVariantPropNames: PlasmicPatientProfile__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPatientProfile__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "patientProfile2") {
    func.displayName = "PlasmicPatientProfile";
  } else {
    func.displayName = `PlasmicPatientProfile.${nodeName}`;
  }
  return func;
}

export const PlasmicPatientProfile = Object.assign(
  // Top-level PlasmicPatientProfile renders the root element
  makeNodeComponent("patientProfile2"),
  {
    // Helper components rendering sub-elements
    redirectToInlabLogin: makeNodeComponent("redirectToInlabLogin"),
    redirectToNamespaceSelection: makeNodeComponent(
      "redirectToNamespaceSelection"
    ),
    header: makeNodeComponent("header"),
    patientProfile: makeNodeComponent("patientProfile"),
    patientData: makeNodeComponent("patientData"),
    patientProfileBox: makeNodeComponent("patientProfileBox"),
    nationalIdAdmissionTimeNoPacs: makeNodeComponent(
      "nationalIdAdmissionTimeNoPacs"
    ),
    nationalId: makeNodeComponent("nationalId"),
    admissionDate: makeNodeComponent("admissionDate"),
    patientNo: makeNodeComponent("patientNo"),
    pacsNumber: makeNodeComponent("pacsNumber"),
    pacsNumber2: makeNodeComponent("pacsNumber2"),
    nameServiceWardBed: makeNodeComponent("nameServiceWardBed"),
    patientName2: makeNodeComponent("patientName2"),
    patientService: makeNodeComponent("patientService"),
    patientWard: makeNodeComponent("patientWard"),
    patientRoomBed: makeNodeComponent("patientRoomBed"),
    freeBox: makeNodeComponent("freeBox"),
    patientStatus: makeNodeComponent("patientStatus"),
    وضعیتبیمار: makeNodeComponent(
      "\u0648\u0636\u0639\u06cc\u062a\u0628\u06cc\u0645\u0627\u0631"
    ),
    bioArcPrescription: makeNodeComponent("bioArcPrescription"),
    switchingTabs: makeNodeComponent("switchingTabs"),
    switchingTab: makeNodeComponent("switchingTab"),
    homepage: makeNodeComponent("homepage"),
    patientProfile5: makeNodeComponent("patientProfile5"),
    radiologyReport: makeNodeComponent("radiologyReport"),
    laboratory: makeNodeComponent("laboratory"),
    bookmarkIcon: makeNodeComponent("bookmarkIcon"),

    // Metadata about props expected for PlasmicPatientProfile
    internalVariantProps: PlasmicPatientProfile__VariantProps,
    internalArgProps: PlasmicPatientProfile__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPatientProfile;
/* prettier-ignore-end */
