// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wjafXWEvDytFogT7SiMy2v
// Component: YivXi3wItkax

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { ApiFetcherComponent } from "../../../utils/ApiFetcherComponent"; // plasmic-import: kxxsrihQ2d7W/codeComponent
import Button from "../../Button"; // plasmic-import: IoZvAstVrNqa/component
import SwitchingTab from "../../SwitchingTab"; // plasmic-import: 9Hr8d57xz9H9/component
import RedirectToLoginPage from "../../RedirectToLoginPage"; // plasmic-import: 0wFpBWYaqpsM/component
import RedirectToNamespaceSelection from "../../RedirectToNamespaceSelection"; // plasmic-import: aXAcva2etiX1/component
import OnloadUserPatientInteractionCount from "../../OnloadUserPatientInteractionCount"; // plasmic-import: 6oEGl3M40QrL/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import { useScreenVariants as useScreenVariantsjEqVmdAbnKYc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jEqVmdAbnKYc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: wjafXWEvDytFogT7SiMy2v/projectcss
import sty from "./PlasmicLaboratoryData.module.css"; // plasmic-import: YivXi3wItkax/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: I6pxicA96WJm/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: vsUaT3pPwdP4/icon

createPlasmicElementProxy;

export type PlasmicLaboratoryData__VariantMembers = {
  viewNormalRange: "viewNormalRange";
  highlightSpecificLabResult: "highlightSpecificLabResult";
};
export type PlasmicLaboratoryData__VariantsArgs = {
  viewNormalRange?: SingleBooleanChoiceArg<"viewNormalRange">;
  highlightSpecificLabResult?: SingleBooleanChoiceArg<"highlightSpecificLabResult">;
};
type VariantPropType = keyof PlasmicLaboratoryData__VariantsArgs;
export const PlasmicLaboratoryData__VariantProps = new Array<VariantPropType>(
  "viewNormalRange",
  "highlightSpecificLabResult"
);

export type PlasmicLaboratoryData__ArgsType = {};
type ArgPropType = keyof PlasmicLaboratoryData__ArgsType;
export const PlasmicLaboratoryData__ArgProps = new Array<ArgPropType>();

export type PlasmicLaboratoryData__OverridesType = {
  laboratoryData?: Flex__<"div">;
  header?: Flex__<"div">;
  patientDataApiFetcher?: Flex__<typeof ApiFetcherComponent>;
  normalRangeButton?: Flex__<typeof Button>;
  labData?: Flex__<typeof ApiFetcherComponent>;
  laboratoryLists?: Flex__<"div">;
  laboratoryTitle?: Flex__<"div">;
  laboratoryResultsPerTitle?: Flex__<"div">;
  labPerDate?: Flex__<"div">;
  reportDatetime?: Flex__<"div">;
  issuedDatetime?: Flex__<"div">;
  labLists?: Flex__<"div">;
  factorNamevalue?: Flex__<"div">;
  factorNamevalue2?: Flex__<"div">;
  factorName?: Flex__<"div">;
  normalFactorValue?: Flex__<"div">;
  abnormalFactorValue?: Flex__<"div">;
  highlightFactorNamevalue3?: Flex__<"div">;
  factorNamevalue4?: Flex__<"div">;
  factorName3?: Flex__<"div">;
  normalFactorValue3?: Flex__<"div">;
  abnormalFactorValue3?: Flex__<"div">;
  normalRanged?: Flex__<"div">;
  switchingTabs?: Flex__<"div">;
  switchingTab?: Flex__<typeof SwitchingTab>;
  redirectToLoginPage?: Flex__<typeof RedirectToLoginPage>;
  redirectToNamespaceSelection?: Flex__<typeof RedirectToNamespaceSelection>;
  onloadUserPatientInteractionCount?: Flex__<
    typeof OnloadUserPatientInteractionCount
  >;
};

export interface DefaultLaboratoryDataProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLaboratoryData__RenderFunc(props: {
  variants: PlasmicLaboratoryData__VariantsArgs;
  args: PlasmicLaboratoryData__ArgsType;
  overrides: PlasmicLaboratoryData__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "viewNormalRange",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.viewNormalRange
      },
      {
        path: "normalRangeButton.isDisabled",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "labFactorId",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0
      },
      {
        path: "highlightSpecificLabResult",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          $props.highlightSpecificLabResult
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjEqVmdAbnKYc()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"laboratoryData"}
        data-plasmic-override={overrides.laboratoryData}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens,
          plasmic_plasmic_rich_components_css.plasmic_tokens,
          sty.laboratoryData,
          {
            [sty.laboratoryDatahighlightSpecificLabResult]: hasVariant(
              $state,
              "highlightSpecificLabResult",
              "highlightSpecificLabResult"
            ),
            [sty.laboratoryDataviewNormalRange]: hasVariant(
              $state,
              "viewNormalRange",
              "viewNormalRange"
            ),
            [sty.laboratoryDataviewNormalRange_highlightSpecificLabResult]:
              hasVariant($state, "viewNormalRange", "viewNormalRange") &&
              hasVariant(
                $state,
                "highlightSpecificLabResult",
                "highlightSpecificLabResult"
              )
          }
        )}
      >
        <div
          data-plasmic-name={"header"}
          data-plasmic-override={overrides.header}
          className={classNames(projectcss.all, sty.header)}
        >
          <ApiFetcherComponent
            data-plasmic-name={"patientDataApiFetcher"}
            data-plasmic-override={overrides.patientDataApiFetcher}
            className={classNames("__wab_instance", sty.patientDataApiFetcher)}
            delay={50}
            headers={(() => {
              try {
                return {
                  "X-Namespace": localStorage.getItem("inlab_user_namespace_id")
                };
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
            method={"GET"}
            path={`/api/v2/patient/${$ctx.params.code}`}
            ref={ref => {
              $refs["patientDataApiFetcher"] = ref;
            }}
          >
            <DataCtxReader__>
              {$ctx => (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__t37T4
                  )}
                >
                  <React.Fragment>
                    {$ctx.fetched_data.loading == false &&
                      (() => {
                        const dob = new Date($ctx.fetched_data.data.dob);
                        const ageDiffMs = Date.now() - dob.getTime();
                        const ageDate = new Date(ageDiffMs);
                        const ageYears = Math.abs(
                          ageDate.getUTCFullYear() - 1970
                        );
                        const fullName = `${$ctx.fetched_data.data.first_name} ${$ctx.fetched_data.data.last_name}`;
                        if (ageYears < 1) {
                          const ageMonths = ageDate.getUTCMonth();
                          return `${fullName} 
${ageMonths} months ${
                            $ctx.fetched_data.data.gender === "F"
                              ? " ♀️"
                              : $ctx.fetched_data.data.gender === "M"
                              ? " ♂️"
                              : ""
                          }`;
                        } else {
                          return `${fullName} 
${ageYears} ${
                            $ctx.fetched_data.data.gender === "F"
                              ? " ♀️"
                              : $ctx.fetched_data.data.gender === "M"
                              ? " ♂️"
                              : ""
                          }`;
                        }
                      })()}
                  </React.Fragment>
                </div>
              )}
            </DataCtxReader__>
          </ApiFetcherComponent>
        </div>
        <Button
          data-plasmic-name={"normalRangeButton"}
          data-plasmic-override={overrides.normalRangeButton}
          className={classNames("__wab_instance", sty.normalRangeButton)}
          color={"blue"}
          isDisabled={generateStateValueProp($state, [
            "normalRangeButton",
            "isDisabled"
          ])}
          onClick={async event => {
            const $steps = {};

            $steps["updateViewNormalRange"] = true
              ? (() => {
                  const actionArgs = {
                    vgroup: "viewNormalRange",
                    operation: 2,
                    value: "viewNormalRange"
                  };
                  return (({ vgroup, value }) => {
                    if (typeof value === "string") {
                      value = [value];
                    }

                    const oldValue = $stateGet($state, vgroup);
                    $stateSet($state, vgroup, !oldValue);
                    return !oldValue;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateViewNormalRange"] != null &&
              typeof $steps["updateViewNormalRange"] === "object" &&
              typeof $steps["updateViewNormalRange"].then === "function"
            ) {
              $steps["updateViewNormalRange"] = await $steps[
                "updateViewNormalRange"
              ];
            }
          }}
          onIsDisabledChange={(...eventArgs) => {
            generateStateOnChangeProp($state, [
              "normalRangeButton",
              "isDisabled"
            ])(eventArgs[0]);
          }}
          shape={"rounded"}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___4D8Ob
            )}
          >
            {"Normal Ranges"}
          </div>
        </Button>
        <ApiFetcherComponent
          data-plasmic-name={"labData"}
          data-plasmic-override={overrides.labData}
          className={classNames("__wab_instance", sty.labData, {
            [sty.labDatahighlightSpecificLabResult]: hasVariant(
              $state,
              "highlightSpecificLabResult",
              "highlightSpecificLabResult"
            ),
            [sty.labDataviewNormalRange]: hasVariant(
              $state,
              "viewNormalRange",
              "viewNormalRange"
            )
          })}
          headers={(() => {
            try {
              return {
                "X-Namespace": localStorage.getItem("inlab_user_namespace_id")
              };
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
          method={"GET"}
          path={`/api/v2/patient/${$ctx.params.code}/raw_lab_tests/recent?offset=0&limit=20`}
          ref={ref => {
            $refs["labData"] = ref;
          }}
        >
          <DataCtxReader__>
            {$ctx => (
              <React.Fragment>
                {$ctx.fetched_data.loading == false &&
                $ctx.fetched_data.data.lab_test_groups == 0 ? (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vcc6L
                    )}
                  >
                    {
                      "\u0622\u0632\u0645\u0627\u06cc\u0634\u06cc \u062b\u0628\u062a \u0646\u0634\u062f\u0647 \u0627\u0633\u062a"
                    }
                  </div>
                ) : null}
                {(() => {
                  try {
                    return $ctx.fetched_data.loading == true;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })() ? (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__woDte
                    )}
                  >
                    {
                      "\u0644\u0637\u0641\u0627 \u0645\u0646\u062a\u0638\u0631 \u0628\u0645\u0627\u0646\u06cc\u062f"
                    }
                  </div>
                ) : null}
                {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                  (() => {
                    try {
                      return $ctx.fetched_data.data.lab_test_groups;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()
                ).map((__plasmic_item_0, __plasmic_idx_0) => {
                  const currentItem = __plasmic_item_0;
                  const currentIndex = __plasmic_idx_0;
                  return (
                    <div
                      data-plasmic-name={"laboratoryLists"}
                      data-plasmic-override={overrides.laboratoryLists}
                      className={classNames(
                        projectcss.all,
                        sty.laboratoryLists,
                        {
                          [sty.laboratoryListshighlightSpecificLabResult]:
                            hasVariant(
                              $state,
                              "highlightSpecificLabResult",
                              "highlightSpecificLabResult"
                            )
                        }
                      )}
                      key={currentIndex}
                    >
                      <div
                        data-plasmic-name={"laboratoryTitle"}
                        data-plasmic-override={overrides.laboratoryTitle}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.laboratoryTitle,
                          {
                            [sty.laboratoryTitlehighlightSpecificLabResult]:
                              hasVariant(
                                $state,
                                "highlightSpecificLabResult",
                                "highlightSpecificLabResult"
                              ),
                            [sty.laboratoryTitleviewNormalRange]: hasVariant(
                              $state,
                              "viewNormalRange",
                              "viewNormalRange"
                            )
                          }
                        )}
                      >
                        <React.Fragment>
                          {currentItem.title.replace(" (  # ) ", "")}
                        </React.Fragment>
                      </div>
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"laboratoryResultsPerTitle"}
                        data-plasmic-override={
                          overrides.laboratoryResultsPerTitle
                        }
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.laboratoryResultsPerTitle,
                          {
                            [sty.laboratoryResultsPerTitlehighlightSpecificLabResult]:
                              hasVariant(
                                $state,
                                "highlightSpecificLabResult",
                                "highlightSpecificLabResult"
                              ),
                            [sty.laboratoryResultsPerTitleviewNormalRange]:
                              hasVariant(
                                $state,
                                "viewNormalRange",
                                "viewNormalRange"
                              ),
                            [sty.laboratoryResultsPerTitleviewNormalRange_highlightSpecificLabResult]:
                              hasVariant(
                                $state,
                                "viewNormalRange",
                                "viewNormalRange"
                              ) &&
                              hasVariant(
                                $state,
                                "highlightSpecificLabResult",
                                "highlightSpecificLabResult"
                              )
                          }
                        )}
                      >
                        {(_par =>
                          !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                          (() => {
                            try {
                              return currentItem.results;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return [];
                              }
                              throw e;
                            }
                          })()
                        ).map((__plasmic_item_1, __plasmic_idx_1) => {
                          const currentItem = __plasmic_item_1;
                          const currentIndex = __plasmic_idx_1;
                          return (
                            <Stack__
                              as={"div"}
                              data-plasmic-name={"labPerDate"}
                              data-plasmic-override={overrides.labPerDate}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.labPerDate,
                                {
                                  [sty.labPerDatehighlightSpecificLabResult]:
                                    hasVariant(
                                      $state,
                                      "highlightSpecificLabResult",
                                      "highlightSpecificLabResult"
                                    ),
                                  [sty.labPerDateviewNormalRange]: hasVariant(
                                    $state,
                                    "viewNormalRange",
                                    "viewNormalRange"
                                  )
                                }
                              )}
                              key={currentIndex}
                            >
                              {currentItem.report_datetime !== null ? (
                                <div
                                  data-plasmic-name={"reportDatetime"}
                                  data-plasmic-override={
                                    overrides.reportDatetime
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.reportDatetime
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      const gregorianDate = new Date(
                                        currentItem.report_datetime
                                      );
                                      const shamsiDate =
                                        new Intl.DateTimeFormat("fa-IR").format(
                                          gregorianDate
                                        );
                                      const shamsiTime =
                                        gregorianDate.toLocaleTimeString(
                                          "fa-IR",
                                          { hour12: false }
                                        );
                                      const englishDate = shamsiDate.replace(
                                        /[۰-۹]/g,
                                        d =>
                                          String.fromCharCode(
                                            d.charCodeAt(0) - 1728
                                          )
                                      );

                                      // Extracting only the hour and minutes from shamsiTime
                                      const englishTime = shamsiTime
                                        .split(":")
                                        .slice(0, 2)
                                        .join(":")
                                        .replace(/[۰-۹]/g, d =>
                                          String.fromCharCode(
                                            d.charCodeAt(0) - 1728
                                          )
                                        );

                                      return `${englishDate}  ${englishTime}`;
                                    })()}
                                  </React.Fragment>
                                </div>
                              ) : null}
                              {currentItem.report_datetime == null ? (
                                <div
                                  data-plasmic-name={"issuedDatetime"}
                                  data-plasmic-override={
                                    overrides.issuedDatetime
                                  }
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.issuedDatetime
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return (() => {
                                          const gregorianDate = new Date(
                                            currentItem.issued_datetime
                                          );
                                          const shamsiDate =
                                            new Intl.DateTimeFormat(
                                              "fa-IR"
                                            ).format(gregorianDate);
                                          const shamsiTime =
                                            gregorianDate.toLocaleTimeString(
                                              "fa-IR",
                                              { hour12: false }
                                            );
                                          const englishDate =
                                            shamsiDate.replace(/[۰-۹]/g, d =>
                                              String.fromCharCode(
                                                d.charCodeAt(0) - 1728
                                              )
                                            );

                                          // Extracting only the hour and minutes from shamsiTime
                                          const englishTime = shamsiTime
                                            .split(":")
                                            .slice(0, 2)
                                            .join(":")
                                            .replace(/[۰-۹]/g, d =>
                                              String.fromCharCode(
                                                d.charCodeAt(0) - 1728
                                              )
                                            );

                                          return `${englishDate}  ${englishTime}`;
                                        })();
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </div>
                              ) : null}
                              {(_par =>
                                !_par
                                  ? []
                                  : Array.isArray(_par)
                                  ? _par
                                  : [_par])(
                                (() => {
                                  try {
                                    return currentItem.values;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return [];
                                    }
                                    throw e;
                                  }
                                })()
                              ).map((__plasmic_item_2, __plasmic_idx_2) => {
                                const currentItem = __plasmic_item_2;
                                const currentIndex = __plasmic_idx_2;
                                return (
                                  <Stack__
                                    as={"div"}
                                    data-plasmic-name={"labLists"}
                                    data-plasmic-override={overrides.labLists}
                                    hasGap={true}
                                    className={classNames(
                                      projectcss.all,
                                      sty.labLists,
                                      {
                                        [sty.labListshighlightSpecificLabResult]:
                                          hasVariant(
                                            $state,
                                            "highlightSpecificLabResult",
                                            "highlightSpecificLabResult"
                                          ),
                                        [sty.labListsviewNormalRange]:
                                          hasVariant(
                                            $state,
                                            "viewNormalRange",
                                            "viewNormalRange"
                                          )
                                      }
                                    )}
                                    key={currentIndex}
                                  >
                                    <Stack__
                                      as={"div"}
                                      data-plasmic-name={"factorNamevalue"}
                                      data-plasmic-override={
                                        overrides.factorNamevalue
                                      }
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.factorNamevalue,
                                        {
                                          [sty.factorNamevaluehighlightSpecificLabResult]:
                                            hasVariant(
                                              $state,
                                              "highlightSpecificLabResult",
                                              "highlightSpecificLabResult"
                                            ),
                                          [sty.factorNamevalueviewNormalRange]:
                                            hasVariant(
                                              $state,
                                              "viewNormalRange",
                                              "viewNormalRange"
                                            ),
                                          [sty.factorNamevalueviewNormalRange_highlightSpecificLabResult]:
                                            hasVariant(
                                              $state,
                                              "viewNormalRange",
                                              "viewNormalRange"
                                            ) &&
                                            hasVariant(
                                              $state,
                                              "highlightSpecificLabResult",
                                              "highlightSpecificLabResult"
                                            )
                                        }
                                      )}
                                      onClick={async event => {
                                        const $steps = {};

                                        $steps["updateLabFactorId"] = true
                                          ? (() => {
                                              const actionArgs = {
                                                variable: {
                                                  objRoot: $state,
                                                  variablePath: ["labFactorId"]
                                                },
                                                operation: 0,
                                                value: currentItem.factor_id
                                              };
                                              return (({
                                                variable,
                                                value,
                                                startIndex,
                                                deleteCount
                                              }) => {
                                                if (!variable) {
                                                  return;
                                                }
                                                const {
                                                  objRoot,
                                                  variablePath
                                                } = variable;

                                                $stateSet(
                                                  objRoot,
                                                  variablePath,
                                                  value
                                                );
                                                return value;
                                              })?.apply(null, [actionArgs]);
                                            })()
                                          : undefined;
                                        if (
                                          $steps["updateLabFactorId"] != null &&
                                          typeof $steps["updateLabFactorId"] ===
                                            "object" &&
                                          typeof $steps["updateLabFactorId"]
                                            .then === "function"
                                        ) {
                                          $steps["updateLabFactorId"] =
                                            await $steps["updateLabFactorId"];
                                        }

                                        $steps[
                                          "updateHighlightSpecificLabResult"
                                        ] = true
                                          ? (() => {
                                              const actionArgs = {
                                                vgroup:
                                                  "highlightSpecificLabResult",
                                                operation: 4
                                              };
                                              return (({ vgroup, value }) => {
                                                if (typeof value === "string") {
                                                  value = [value];
                                                }

                                                $stateSet($state, vgroup, true);
                                                return true;
                                              })?.apply(null, [actionArgs]);
                                            })()
                                          : undefined;
                                        if (
                                          $steps[
                                            "updateHighlightSpecificLabResult"
                                          ] != null &&
                                          typeof $steps[
                                            "updateHighlightSpecificLabResult"
                                          ] === "object" &&
                                          typeof $steps[
                                            "updateHighlightSpecificLabResult"
                                          ].then === "function"
                                        ) {
                                          $steps[
                                            "updateHighlightSpecificLabResult"
                                          ] = await $steps[
                                            "updateHighlightSpecificLabResult"
                                          ];
                                        }
                                      }}
                                    >
                                      <Stack__
                                        as={"div"}
                                        data-plasmic-name={"factorNamevalue2"}
                                        data-plasmic-override={
                                          overrides.factorNamevalue2
                                        }
                                        hasGap={true}
                                        className={classNames(
                                          projectcss.all,
                                          sty.factorNamevalue2,
                                          {
                                            [sty.factorNamevalue2highlightSpecificLabResult]:
                                              hasVariant(
                                                $state,
                                                "highlightSpecificLabResult",
                                                "highlightSpecificLabResult"
                                              ),
                                            [sty.factorNamevalue2viewNormalRange]:
                                              hasVariant(
                                                $state,
                                                "viewNormalRange",
                                                "viewNormalRange"
                                              ),
                                            [sty.factorNamevalue2viewNormalRange_highlightSpecificLabResult]:
                                              hasVariant(
                                                $state,
                                                "viewNormalRange",
                                                "viewNormalRange"
                                              ) &&
                                              hasVariant(
                                                $state,
                                                "highlightSpecificLabResult",
                                                "highlightSpecificLabResult"
                                              )
                                          }
                                        )}
                                      >
                                        <div
                                          data-plasmic-name={"factorName"}
                                          data-plasmic-override={
                                            overrides.factorName
                                          }
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.__wab_text,
                                            sty.factorName,
                                            {
                                              [sty.factorNamehighlightSpecificLabResult]:
                                                hasVariant(
                                                  $state,
                                                  "highlightSpecificLabResult",
                                                  "highlightSpecificLabResult"
                                                ),
                                              [sty.factorNameviewNormalRange]:
                                                hasVariant(
                                                  $state,
                                                  "viewNormalRange",
                                                  "viewNormalRange"
                                                ),
                                              [sty.factorNameviewNormalRange_highlightSpecificLabResult]:
                                                hasVariant(
                                                  $state,
                                                  "viewNormalRange",
                                                  "viewNormalRange"
                                                ) &&
                                                hasVariant(
                                                  $state,
                                                  "highlightSpecificLabResult",
                                                  "highlightSpecificLabResult"
                                                )
                                            }
                                          )}
                                        >
                                          <React.Fragment>
                                            {currentItem.factor_name.replace(
                                              " (  # )",
                                              "",
                                              "(#*)"
                                            )}
                                          </React.Fragment>
                                        </div>
                                        {currentItem.abnormal == false ? (
                                          <div
                                            data-plasmic-name={
                                              "normalFactorValue"
                                            }
                                            data-plasmic-override={
                                              overrides.normalFactorValue
                                            }
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.__wab_text,
                                              sty.normalFactorValue,
                                              {
                                                [sty.normalFactorValuehighlightSpecificLabResult]:
                                                  hasVariant(
                                                    $state,
                                                    "highlightSpecificLabResult",
                                                    "highlightSpecificLabResult"
                                                  )
                                              }
                                            )}
                                          >
                                            <React.Fragment>
                                              {currentItem.value}
                                            </React.Fragment>
                                          </div>
                                        ) : null}
                                        {(
                                          hasVariant(
                                            $state,
                                            "viewNormalRange",
                                            "viewNormalRange"
                                          ) &&
                                          hasVariant(
                                            $state,
                                            "highlightSpecificLabResult",
                                            "highlightSpecificLabResult"
                                          )
                                            ? true
                                            : currentItem.abnormal == true
                                        ) ? (
                                          <div
                                            data-plasmic-name={
                                              "abnormalFactorValue"
                                            }
                                            data-plasmic-override={
                                              overrides.abnormalFactorValue
                                            }
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.__wab_text,
                                              sty.abnormalFactorValue,
                                              {
                                                [sty.abnormalFactorValueviewNormalRange_highlightSpecificLabResult]:
                                                  hasVariant(
                                                    $state,
                                                    "viewNormalRange",
                                                    "viewNormalRange"
                                                  ) &&
                                                  hasVariant(
                                                    $state,
                                                    "highlightSpecificLabResult",
                                                    "highlightSpecificLabResult"
                                                  )
                                              }
                                            )}
                                          >
                                            <React.Fragment>
                                              {currentItem.value}
                                            </React.Fragment>
                                          </div>
                                        ) : null}
                                      </Stack__>
                                    </Stack__>
                                    {(
                                      hasVariant(
                                        $state,
                                        "highlightSpecificLabResult",
                                        "highlightSpecificLabResult"
                                      )
                                        ? (() => {
                                            try {
                                              return (
                                                currentItem.factor_id ==
                                                $state.labFactorId
                                              );
                                            } catch (e) {
                                              if (
                                                e instanceof TypeError ||
                                                e?.plasmicType ===
                                                  "PlasmicUndefinedDataError"
                                              ) {
                                                return true;
                                              }
                                              throw e;
                                            }
                                          })()
                                        : false
                                    ) ? (
                                      <Stack__
                                        as={"div"}
                                        data-plasmic-name={
                                          "highlightFactorNamevalue3"
                                        }
                                        data-plasmic-override={
                                          overrides.highlightFactorNamevalue3
                                        }
                                        hasGap={true}
                                        className={classNames(
                                          projectcss.all,
                                          sty.highlightFactorNamevalue3,
                                          {
                                            [sty.highlightFactorNamevalue3highlightSpecificLabResult]:
                                              hasVariant(
                                                $state,
                                                "highlightSpecificLabResult",
                                                "highlightSpecificLabResult"
                                              ),
                                            [sty.highlightFactorNamevalue3viewNormalRange]:
                                              hasVariant(
                                                $state,
                                                "viewNormalRange",
                                                "viewNormalRange"
                                              ),
                                            [sty.highlightFactorNamevalue3viewNormalRange_highlightSpecificLabResult]:
                                              hasVariant(
                                                $state,
                                                "viewNormalRange",
                                                "viewNormalRange"
                                              ) &&
                                              hasVariant(
                                                $state,
                                                "highlightSpecificLabResult",
                                                "highlightSpecificLabResult"
                                              )
                                          }
                                        )}
                                        onClick={async event => {
                                          const $steps = {};

                                          $steps["updateLabFactorId"] = true
                                            ? (() => {
                                                const actionArgs = {
                                                  variable: {
                                                    objRoot: $state,
                                                    variablePath: [
                                                      "labFactorId"
                                                    ]
                                                  },
                                                  operation: 0,
                                                  value: currentItem.factor_id
                                                };
                                                return (({
                                                  variable,
                                                  value,
                                                  startIndex,
                                                  deleteCount
                                                }) => {
                                                  if (!variable) {
                                                    return;
                                                  }
                                                  const {
                                                    objRoot,
                                                    variablePath
                                                  } = variable;

                                                  $stateSet(
                                                    objRoot,
                                                    variablePath,
                                                    value
                                                  );
                                                  return value;
                                                })?.apply(null, [actionArgs]);
                                              })()
                                            : undefined;
                                          if (
                                            $steps["updateLabFactorId"] !=
                                              null &&
                                            typeof $steps[
                                              "updateLabFactorId"
                                            ] === "object" &&
                                            typeof $steps["updateLabFactorId"]
                                              .then === "function"
                                          ) {
                                            $steps["updateLabFactorId"] =
                                              await $steps["updateLabFactorId"];
                                          }

                                          $steps[
                                            "updateHighlightSpecificLabResult"
                                          ] = true
                                            ? (() => {
                                                const actionArgs = {
                                                  vgroup:
                                                    "highlightSpecificLabResult",
                                                  operation: 4
                                                };
                                                return (({ vgroup, value }) => {
                                                  if (
                                                    typeof value === "string"
                                                  ) {
                                                    value = [value];
                                                  }

                                                  $stateSet(
                                                    $state,
                                                    vgroup,
                                                    true
                                                  );
                                                  return true;
                                                })?.apply(null, [actionArgs]);
                                              })()
                                            : undefined;
                                          if (
                                            $steps[
                                              "updateHighlightSpecificLabResult"
                                            ] != null &&
                                            typeof $steps[
                                              "updateHighlightSpecificLabResult"
                                            ] === "object" &&
                                            typeof $steps[
                                              "updateHighlightSpecificLabResult"
                                            ].then === "function"
                                          ) {
                                            $steps[
                                              "updateHighlightSpecificLabResult"
                                            ] = await $steps[
                                              "updateHighlightSpecificLabResult"
                                            ];
                                          }
                                        }}
                                      >
                                        <Stack__
                                          as={"div"}
                                          data-plasmic-name={"factorNamevalue4"}
                                          data-plasmic-override={
                                            overrides.factorNamevalue4
                                          }
                                          hasGap={true}
                                          className={classNames(
                                            projectcss.all,
                                            sty.factorNamevalue4,
                                            {
                                              [sty.factorNamevalue4highlightSpecificLabResult]:
                                                hasVariant(
                                                  $state,
                                                  "highlightSpecificLabResult",
                                                  "highlightSpecificLabResult"
                                                ),
                                              [sty.factorNamevalue4viewNormalRange]:
                                                hasVariant(
                                                  $state,
                                                  "viewNormalRange",
                                                  "viewNormalRange"
                                                ),
                                              [sty.factorNamevalue4viewNormalRange_highlightSpecificLabResult]:
                                                hasVariant(
                                                  $state,
                                                  "viewNormalRange",
                                                  "viewNormalRange"
                                                ) &&
                                                hasVariant(
                                                  $state,
                                                  "highlightSpecificLabResult",
                                                  "highlightSpecificLabResult"
                                                )
                                            }
                                          )}
                                        >
                                          <div
                                            data-plasmic-name={"factorName3"}
                                            data-plasmic-override={
                                              overrides.factorName3
                                            }
                                            className={classNames(
                                              projectcss.all,
                                              projectcss.__wab_text,
                                              sty.factorName3,
                                              {
                                                [sty.factorName3highlightSpecificLabResult]:
                                                  hasVariant(
                                                    $state,
                                                    "highlightSpecificLabResult",
                                                    "highlightSpecificLabResult"
                                                  ),
                                                [sty.factorName3viewNormalRange]:
                                                  hasVariant(
                                                    $state,
                                                    "viewNormalRange",
                                                    "viewNormalRange"
                                                  ),
                                                [sty.factorName3viewNormalRange_highlightSpecificLabResult]:
                                                  hasVariant(
                                                    $state,
                                                    "viewNormalRange",
                                                    "viewNormalRange"
                                                  ) &&
                                                  hasVariant(
                                                    $state,
                                                    "highlightSpecificLabResult",
                                                    "highlightSpecificLabResult"
                                                  )
                                              }
                                            )}
                                          >
                                            <React.Fragment>
                                              {currentItem.factor_name.replace(
                                                " (  # )",
                                                "",
                                                "(#*)"
                                              )}
                                            </React.Fragment>
                                          </div>
                                          {currentItem.abnormal == false ? (
                                            <div
                                              data-plasmic-name={
                                                "normalFactorValue3"
                                              }
                                              data-plasmic-override={
                                                overrides.normalFactorValue3
                                              }
                                              className={classNames(
                                                projectcss.all,
                                                projectcss.__wab_text,
                                                sty.normalFactorValue3,
                                                {
                                                  [sty.normalFactorValue3highlightSpecificLabResult]:
                                                    hasVariant(
                                                      $state,
                                                      "highlightSpecificLabResult",
                                                      "highlightSpecificLabResult"
                                                    )
                                                }
                                              )}
                                            >
                                              <React.Fragment>
                                                {currentItem.value}
                                              </React.Fragment>
                                            </div>
                                          ) : null}
                                          {(
                                            hasVariant(
                                              $state,
                                              "viewNormalRange",
                                              "viewNormalRange"
                                            ) &&
                                            hasVariant(
                                              $state,
                                              "highlightSpecificLabResult",
                                              "highlightSpecificLabResult"
                                            )
                                              ? true
                                              : currentItem.abnormal == true
                                          ) ? (
                                            <div
                                              data-plasmic-name={
                                                "abnormalFactorValue3"
                                              }
                                              data-plasmic-override={
                                                overrides.abnormalFactorValue3
                                              }
                                              className={classNames(
                                                projectcss.all,
                                                projectcss.__wab_text,
                                                sty.abnormalFactorValue3,
                                                {
                                                  [sty.abnormalFactorValue3viewNormalRange_highlightSpecificLabResult]:
                                                    hasVariant(
                                                      $state,
                                                      "viewNormalRange",
                                                      "viewNormalRange"
                                                    ) &&
                                                    hasVariant(
                                                      $state,
                                                      "highlightSpecificLabResult",
                                                      "highlightSpecificLabResult"
                                                    )
                                                }
                                              )}
                                            >
                                              <React.Fragment>
                                                {currentItem.value}
                                              </React.Fragment>
                                            </div>
                                          ) : null}
                                        </Stack__>
                                      </Stack__>
                                    ) : null}
                                    {(
                                      hasVariant(
                                        $state,
                                        "viewNormalRange",
                                        "viewNormalRange"
                                      ) &&
                                      hasVariant(
                                        $state,
                                        "highlightSpecificLabResult",
                                        "highlightSpecificLabResult"
                                      )
                                        ? true
                                        : hasVariant(
                                            $state,
                                            "highlightSpecificLabResult",
                                            "highlightSpecificLabResult"
                                          )
                                        ? $state.normalRangeButton.isDisabled
                                        : hasVariant(
                                            $state,
                                            "viewNormalRange",
                                            "viewNormalRange"
                                          )
                                        ? true
                                        : true
                                    ) ? (
                                      <div
                                        data-plasmic-name={"normalRanged"}
                                        data-plasmic-override={
                                          overrides.normalRanged
                                        }
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.normalRanged,
                                          {
                                            [sty.normalRangedhighlightSpecificLabResult]:
                                              hasVariant(
                                                $state,
                                                "highlightSpecificLabResult",
                                                "highlightSpecificLabResult"
                                              ),
                                            [sty.normalRangedviewNormalRange]:
                                              hasVariant(
                                                $state,
                                                "viewNormalRange",
                                                "viewNormalRange"
                                              ),
                                            [sty.normalRangedviewNormalRange_highlightSpecificLabResult]:
                                              hasVariant(
                                                $state,
                                                "viewNormalRange",
                                                "viewNormalRange"
                                              ) &&
                                              hasVariant(
                                                $state,
                                                "highlightSpecificLabResult",
                                                "highlightSpecificLabResult"
                                              )
                                          }
                                        )}
                                      >
                                        <React.Fragment>
                                          {currentItem.normal_range}
                                        </React.Fragment>
                                      </div>
                                    ) : null}
                                  </Stack__>
                                );
                              })}
                            </Stack__>
                          );
                        })}
                      </Stack__>
                    </div>
                  );
                })}
              </React.Fragment>
            )}
          </DataCtxReader__>
        </ApiFetcherComponent>
        <div
          data-plasmic-name={"switchingTabs"}
          data-plasmic-override={overrides.switchingTabs}
          className={classNames(projectcss.all, sty.switchingTabs)}
        >
          <SwitchingTab
            data-plasmic-name={"switchingTab"}
            data-plasmic-override={overrides.switchingTab}
            className={classNames("__wab_instance", sty.switchingTab)}
          />
        </div>
        <RedirectToLoginPage
          data-plasmic-name={"redirectToLoginPage"}
          data-plasmic-override={overrides.redirectToLoginPage}
          className={classNames("__wab_instance", sty.redirectToLoginPage)}
        />

        <RedirectToNamespaceSelection
          data-plasmic-name={"redirectToNamespaceSelection"}
          data-plasmic-override={overrides.redirectToNamespaceSelection}
          className={classNames(
            "__wab_instance",
            sty.redirectToNamespaceSelection
          )}
        />

        <OnloadUserPatientInteractionCount
          data-plasmic-name={"onloadUserPatientInteractionCount"}
          data-plasmic-override={overrides.onloadUserPatientInteractionCount}
          className={classNames(
            "__wab_instance",
            sty.onloadUserPatientInteractionCount
          )}
          patientIdForOnloadUserPatientInteractionCount={(() => {
            try {
              return $ctx.params.code;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  laboratoryData: [
    "laboratoryData",
    "header",
    "patientDataApiFetcher",
    "normalRangeButton",
    "labData",
    "laboratoryLists",
    "laboratoryTitle",
    "laboratoryResultsPerTitle",
    "labPerDate",
    "reportDatetime",
    "issuedDatetime",
    "labLists",
    "factorNamevalue",
    "factorNamevalue2",
    "factorName",
    "normalFactorValue",
    "abnormalFactorValue",
    "highlightFactorNamevalue3",
    "factorNamevalue4",
    "factorName3",
    "normalFactorValue3",
    "abnormalFactorValue3",
    "normalRanged",
    "switchingTabs",
    "switchingTab",
    "redirectToLoginPage",
    "redirectToNamespaceSelection",
    "onloadUserPatientInteractionCount"
  ],
  header: ["header", "patientDataApiFetcher"],
  patientDataApiFetcher: ["patientDataApiFetcher"],
  normalRangeButton: ["normalRangeButton"],
  labData: [
    "labData",
    "laboratoryLists",
    "laboratoryTitle",
    "laboratoryResultsPerTitle",
    "labPerDate",
    "reportDatetime",
    "issuedDatetime",
    "labLists",
    "factorNamevalue",
    "factorNamevalue2",
    "factorName",
    "normalFactorValue",
    "abnormalFactorValue",
    "highlightFactorNamevalue3",
    "factorNamevalue4",
    "factorName3",
    "normalFactorValue3",
    "abnormalFactorValue3",
    "normalRanged"
  ],
  laboratoryLists: [
    "laboratoryLists",
    "laboratoryTitle",
    "laboratoryResultsPerTitle",
    "labPerDate",
    "reportDatetime",
    "issuedDatetime",
    "labLists",
    "factorNamevalue",
    "factorNamevalue2",
    "factorName",
    "normalFactorValue",
    "abnormalFactorValue",
    "highlightFactorNamevalue3",
    "factorNamevalue4",
    "factorName3",
    "normalFactorValue3",
    "abnormalFactorValue3",
    "normalRanged"
  ],
  laboratoryTitle: ["laboratoryTitle"],
  laboratoryResultsPerTitle: [
    "laboratoryResultsPerTitle",
    "labPerDate",
    "reportDatetime",
    "issuedDatetime",
    "labLists",
    "factorNamevalue",
    "factorNamevalue2",
    "factorName",
    "normalFactorValue",
    "abnormalFactorValue",
    "highlightFactorNamevalue3",
    "factorNamevalue4",
    "factorName3",
    "normalFactorValue3",
    "abnormalFactorValue3",
    "normalRanged"
  ],
  labPerDate: [
    "labPerDate",
    "reportDatetime",
    "issuedDatetime",
    "labLists",
    "factorNamevalue",
    "factorNamevalue2",
    "factorName",
    "normalFactorValue",
    "abnormalFactorValue",
    "highlightFactorNamevalue3",
    "factorNamevalue4",
    "factorName3",
    "normalFactorValue3",
    "abnormalFactorValue3",
    "normalRanged"
  ],
  reportDatetime: ["reportDatetime"],
  issuedDatetime: ["issuedDatetime"],
  labLists: [
    "labLists",
    "factorNamevalue",
    "factorNamevalue2",
    "factorName",
    "normalFactorValue",
    "abnormalFactorValue",
    "highlightFactorNamevalue3",
    "factorNamevalue4",
    "factorName3",
    "normalFactorValue3",
    "abnormalFactorValue3",
    "normalRanged"
  ],
  factorNamevalue: [
    "factorNamevalue",
    "factorNamevalue2",
    "factorName",
    "normalFactorValue",
    "abnormalFactorValue"
  ],
  factorNamevalue2: [
    "factorNamevalue2",
    "factorName",
    "normalFactorValue",
    "abnormalFactorValue"
  ],
  factorName: ["factorName"],
  normalFactorValue: ["normalFactorValue"],
  abnormalFactorValue: ["abnormalFactorValue"],
  highlightFactorNamevalue3: [
    "highlightFactorNamevalue3",
    "factorNamevalue4",
    "factorName3",
    "normalFactorValue3",
    "abnormalFactorValue3"
  ],
  factorNamevalue4: [
    "factorNamevalue4",
    "factorName3",
    "normalFactorValue3",
    "abnormalFactorValue3"
  ],
  factorName3: ["factorName3"],
  normalFactorValue3: ["normalFactorValue3"],
  abnormalFactorValue3: ["abnormalFactorValue3"],
  normalRanged: ["normalRanged"],
  switchingTabs: ["switchingTabs", "switchingTab"],
  switchingTab: ["switchingTab"],
  redirectToLoginPage: ["redirectToLoginPage"],
  redirectToNamespaceSelection: ["redirectToNamespaceSelection"],
  onloadUserPatientInteractionCount: ["onloadUserPatientInteractionCount"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  laboratoryData: "div";
  header: "div";
  patientDataApiFetcher: typeof ApiFetcherComponent;
  normalRangeButton: typeof Button;
  labData: typeof ApiFetcherComponent;
  laboratoryLists: "div";
  laboratoryTitle: "div";
  laboratoryResultsPerTitle: "div";
  labPerDate: "div";
  reportDatetime: "div";
  issuedDatetime: "div";
  labLists: "div";
  factorNamevalue: "div";
  factorNamevalue2: "div";
  factorName: "div";
  normalFactorValue: "div";
  abnormalFactorValue: "div";
  highlightFactorNamevalue3: "div";
  factorNamevalue4: "div";
  factorName3: "div";
  normalFactorValue3: "div";
  abnormalFactorValue3: "div";
  normalRanged: "div";
  switchingTabs: "div";
  switchingTab: typeof SwitchingTab;
  redirectToLoginPage: typeof RedirectToLoginPage;
  redirectToNamespaceSelection: typeof RedirectToNamespaceSelection;
  onloadUserPatientInteractionCount: typeof OnloadUserPatientInteractionCount;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLaboratoryData__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLaboratoryData__VariantsArgs;
    args?: PlasmicLaboratoryData__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLaboratoryData__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicLaboratoryData__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLaboratoryData__ArgProps,
          internalVariantPropNames: PlasmicLaboratoryData__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLaboratoryData__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "laboratoryData") {
    func.displayName = "PlasmicLaboratoryData";
  } else {
    func.displayName = `PlasmicLaboratoryData.${nodeName}`;
  }
  return func;
}

export const PlasmicLaboratoryData = Object.assign(
  // Top-level PlasmicLaboratoryData renders the root element
  makeNodeComponent("laboratoryData"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    patientDataApiFetcher: makeNodeComponent("patientDataApiFetcher"),
    normalRangeButton: makeNodeComponent("normalRangeButton"),
    labData: makeNodeComponent("labData"),
    laboratoryLists: makeNodeComponent("laboratoryLists"),
    laboratoryTitle: makeNodeComponent("laboratoryTitle"),
    laboratoryResultsPerTitle: makeNodeComponent("laboratoryResultsPerTitle"),
    labPerDate: makeNodeComponent("labPerDate"),
    reportDatetime: makeNodeComponent("reportDatetime"),
    issuedDatetime: makeNodeComponent("issuedDatetime"),
    labLists: makeNodeComponent("labLists"),
    factorNamevalue: makeNodeComponent("factorNamevalue"),
    factorNamevalue2: makeNodeComponent("factorNamevalue2"),
    factorName: makeNodeComponent("factorName"),
    normalFactorValue: makeNodeComponent("normalFactorValue"),
    abnormalFactorValue: makeNodeComponent("abnormalFactorValue"),
    highlightFactorNamevalue3: makeNodeComponent("highlightFactorNamevalue3"),
    factorNamevalue4: makeNodeComponent("factorNamevalue4"),
    factorName3: makeNodeComponent("factorName3"),
    normalFactorValue3: makeNodeComponent("normalFactorValue3"),
    abnormalFactorValue3: makeNodeComponent("abnormalFactorValue3"),
    normalRanged: makeNodeComponent("normalRanged"),
    switchingTabs: makeNodeComponent("switchingTabs"),
    switchingTab: makeNodeComponent("switchingTab"),
    redirectToLoginPage: makeNodeComponent("redirectToLoginPage"),
    redirectToNamespaceSelection: makeNodeComponent(
      "redirectToNamespaceSelection"
    ),
    onloadUserPatientInteractionCount: makeNodeComponent(
      "onloadUserPatientInteractionCount"
    ),

    // Metadata about props expected for PlasmicLaboratoryData
    internalVariantProps: PlasmicLaboratoryData__VariantProps,
    internalArgProps: PlasmicLaboratoryData__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicLaboratoryData;
/* prettier-ignore-end */
