// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wjafXWEvDytFogT7SiMy2v
// Component: x1Fxn6tnPsJ0

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { SideEffect } from "@plasmicpkgs/plasmic-basic-components";

import { useScreenVariants as useScreenVariantsjEqVmdAbnKYc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jEqVmdAbnKYc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_inlab.module.css"; // plasmic-import: wjafXWEvDytFogT7SiMy2v/projectcss
import sty from "./PlasmicRedirectRootPageToHomepage.module.css"; // plasmic-import: x1Fxn6tnPsJ0/css

createPlasmicElementProxy;

export type PlasmicRedirectRootPageToHomepage__VariantMembers = {};
export type PlasmicRedirectRootPageToHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicRedirectRootPageToHomepage__VariantsArgs;
export const PlasmicRedirectRootPageToHomepage__VariantProps =
  new Array<VariantPropType>();

export type PlasmicRedirectRootPageToHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicRedirectRootPageToHomepage__ArgsType;
export const PlasmicRedirectRootPageToHomepage__ArgProps =
  new Array<ArgPropType>();

export type PlasmicRedirectRootPageToHomepage__OverridesType = {
  redirectRootPageToHomepage?: Flex__<typeof SideEffect>;
};

export interface DefaultRedirectRootPageToHomepageProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRedirectRootPageToHomepage__RenderFunc(props: {
  variants: PlasmicRedirectRootPageToHomepage__VariantsArgs;
  args: PlasmicRedirectRootPageToHomepage__ArgsType;
  overrides: PlasmicRedirectRootPageToHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjEqVmdAbnKYc()
  });

  return (
    <SideEffect
      data-plasmic-name={"redirectRootPageToHomepage"}
      data-plasmic-override={overrides.redirectRootPageToHomepage}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.redirectRootPageToHomepage
      )}
      onMount={async () => {
        const $steps = {};

        $steps["consoleLogOfInlabUser"] = true
          ? (() => {
              const actionArgs = {
                customFunction: async () => {
                  return console.log(
                    `inlab_user: ${localStorage.getItem("inlab_user")}`
                  );
                }
              };
              return (({ customFunction }) => {
                return customFunction();
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["consoleLogOfInlabUser"] != null &&
          typeof $steps["consoleLogOfInlabUser"] === "object" &&
          typeof $steps["consoleLogOfInlabUser"].then === "function"
        ) {
          $steps["consoleLogOfInlabUser"] = await $steps[
            "consoleLogOfInlabUser"
          ];
        }

        $steps["consoleLogOfInlabUserNamespaceId"] = true
          ? (() => {
              const actionArgs = {
                customFunction: async () => {
                  return console.log(
                    `inlab_user_namespace_id: ${localStorage.getItem(
                      "inlab_user_namespace_id"
                    )}`
                  );
                }
              };
              return (({ customFunction }) => {
                return customFunction();
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["consoleLogOfInlabUserNamespaceId"] != null &&
          typeof $steps["consoleLogOfInlabUserNamespaceId"] === "object" &&
          typeof $steps["consoleLogOfInlabUserNamespaceId"].then === "function"
        ) {
          $steps["consoleLogOfInlabUserNamespaceId"] = await $steps[
            "consoleLogOfInlabUserNamespaceId"
          ];
        }

        $steps["goToHomepage"] =
          localStorage.getItem("inlab_user") &&
          localStorage.getItem("inlab_user_namespace_id")
            ? (() => {
                const actionArgs = { destination: `/patients` };
                return (({ destination }) => {
                  if (
                    typeof destination === "string" &&
                    destination.startsWith("#")
                  ) {
                    document
                      .getElementById(destination.substr(1))
                      .scrollIntoView({ behavior: "smooth" });
                  } else {
                    __nextRouter?.push(destination);
                  }
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
        if (
          $steps["goToHomepage"] != null &&
          typeof $steps["goToHomepage"] === "object" &&
          typeof $steps["goToHomepage"].then === "function"
        ) {
          $steps["goToHomepage"] = await $steps["goToHomepage"];
        }
      }}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  redirectRootPageToHomepage: ["redirectRootPageToHomepage"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  redirectRootPageToHomepage: typeof SideEffect;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRedirectRootPageToHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRedirectRootPageToHomepage__VariantsArgs;
    args?: PlasmicRedirectRootPageToHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRedirectRootPageToHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicRedirectRootPageToHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicRedirectRootPageToHomepage__ArgProps,
          internalVariantPropNames:
            PlasmicRedirectRootPageToHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRedirectRootPageToHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "redirectRootPageToHomepage") {
    func.displayName = "PlasmicRedirectRootPageToHomepage";
  } else {
    func.displayName = `PlasmicRedirectRootPageToHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicRedirectRootPageToHomepage = Object.assign(
  // Top-level PlasmicRedirectRootPageToHomepage renders the root element
  makeNodeComponent("redirectRootPageToHomepage"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicRedirectRootPageToHomepage
    internalVariantProps: PlasmicRedirectRootPageToHomepage__VariantProps,
    internalArgProps: PlasmicRedirectRootPageToHomepage__ArgProps
  }
);

export default PlasmicRedirectRootPageToHomepage;
/* prettier-ignore-end */
