// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wjafXWEvDytFogT7SiMy2v
// Component: QnDyAyhvLYc4

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import H from "../../H"; // plasmic-import: -ckcELWzdUW7/component
import SwitchingTab from "../../SwitchingTab"; // plasmic-import: 9Hr8d57xz9H9/component
import RedirectUserToLoginPage from "../../RedirectUserToLoginPage"; // plasmic-import: 0wFpBWYaqpsM/component

import { useScreenVariants as useScreenVariantsjEqVmdAbnKYc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jEqVmdAbnKYc/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_inlab.module.css"; // plasmic-import: wjafXWEvDytFogT7SiMy2v/projectcss
import sty from "./PlasmicImagingReports2.module.css"; // plasmic-import: QnDyAyhvLYc4/css

createPlasmicElementProxy;

export type PlasmicImagingReports2__VariantMembers = {};
export type PlasmicImagingReports2__VariantsArgs = {};
type VariantPropType = keyof PlasmicImagingReports2__VariantsArgs;
export const PlasmicImagingReports2__VariantProps =
  new Array<VariantPropType>();

export type PlasmicImagingReports2__ArgsType = {
  patientProfileHeader?: React.ReactNode;
};
type ArgPropType = keyof PlasmicImagingReports2__ArgsType;
export const PlasmicImagingReports2__ArgProps = new Array<ArgPropType>(
  "patientProfileHeader"
);

export type PlasmicImagingReports2__OverridesType = {
  imagingReports2?: p.Flex<"div">;
  imagingReport2?: p.Flex<"div">;
  imagingReport?: p.Flex<"div">;
  switchingTabs?: p.Flex<"div">;
  switchingTab?: p.Flex<typeof SwitchingTab>;
  redirectUserToLoginPage?: p.Flex<typeof RedirectUserToLoginPage>;
};

export interface DefaultImagingReports2Props {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicImagingReports2__RenderFunc(props: {
  variants: PlasmicImagingReports2__VariantsArgs;
  args: PlasmicImagingReports2__ArgsType;
  overrides: PlasmicImagingReports2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjEqVmdAbnKYc()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"imagingReports2"}
          data-plasmic-override={overrides.imagingReports2}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.imagingReports2
          )}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <H className={classNames("__wab_instance", sty.h__nPaKt)} />
            ),

            value: args.patientProfileHeader
          })}
          <p.Stack
            as={"div"}
            data-plasmic-name={"imagingReport2"}
            data-plasmic-override={overrides.imagingReport2}
            hasGap={true}
            className={classNames(projectcss.all, sty.imagingReport2)}
          >
            <div
              data-plasmic-name={"imagingReport"}
              data-plasmic-override={overrides.imagingReport}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.imagingReport
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $ctx.params.imaging_report;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </p.Stack>
          <div
            data-plasmic-name={"switchingTabs"}
            data-plasmic-override={overrides.switchingTabs}
            className={classNames(projectcss.all, sty.switchingTabs)}
          >
            <SwitchingTab
              data-plasmic-name={"switchingTab"}
              data-plasmic-override={overrides.switchingTab}
              className={classNames("__wab_instance", sty.switchingTab)}
            />
          </div>
          <RedirectUserToLoginPage
            data-plasmic-name={"redirectUserToLoginPage"}
            data-plasmic-override={overrides.redirectUserToLoginPage}
            className={classNames(
              "__wab_instance",
              sty.redirectUserToLoginPage
            )}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  imagingReports2: [
    "imagingReports2",
    "imagingReport2",
    "imagingReport",
    "switchingTabs",
    "switchingTab",
    "redirectUserToLoginPage"
  ],
  imagingReport2: ["imagingReport2", "imagingReport"],
  imagingReport: ["imagingReport"],
  switchingTabs: ["switchingTabs", "switchingTab"],
  switchingTab: ["switchingTab"],
  redirectUserToLoginPage: ["redirectUserToLoginPage"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  imagingReports2: "div";
  imagingReport2: "div";
  imagingReport: "div";
  switchingTabs: "div";
  switchingTab: typeof SwitchingTab;
  redirectUserToLoginPage: typeof RedirectUserToLoginPage;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicImagingReports2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicImagingReports2__VariantsArgs;
    args?: PlasmicImagingReports2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicImagingReports2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicImagingReports2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicImagingReports2__ArgProps,
          internalVariantPropNames: PlasmicImagingReports2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicImagingReports2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "imagingReports2") {
    func.displayName = "PlasmicImagingReports2";
  } else {
    func.displayName = `PlasmicImagingReports2.${nodeName}`;
  }
  return func;
}

export const PlasmicImagingReports2 = Object.assign(
  // Top-level PlasmicImagingReports2 renders the root element
  makeNodeComponent("imagingReports2"),
  {
    // Helper components rendering sub-elements
    imagingReport2: makeNodeComponent("imagingReport2"),
    imagingReport: makeNodeComponent("imagingReport"),
    switchingTabs: makeNodeComponent("switchingTabs"),
    switchingTab: makeNodeComponent("switchingTab"),
    redirectUserToLoginPage: makeNodeComponent("redirectUserToLoginPage"),

    // Metadata about props expected for PlasmicImagingReports2
    internalVariantProps: PlasmicImagingReports2__VariantProps,
    internalArgProps: PlasmicImagingReports2__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicImagingReports2;
/* prettier-ignore-end */
